<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "amazon_s3" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Amazon S3' => 'Amazon S3',
    'Common' => 'Allgemein',
    'Customers' => 'Kunden',
    'Uploaded email templates' => 'Hochgeladene E-Mail-Vorlagen',
    'S3 access key' => 'S3-Zugriffsschlüssel',
    'S3 access secret' => 'S3-Zugriffsgeheimnis',
    'S3 region' => 'S3-Region',
    'Enabled for customers' => 'Für Kunden aktiviert',
    'Customers use system S3 account' => 'Kunden verwenden das System-S3-Konto',
    'Customers add own S3 account' => 'Kunden fügen eigenes S3-Konto hinzu',
    'Bucket name' => 'Bucket-Name',
    'The access key for Amazon S3 service' => 'Der Zugriffsschlüssel für den Amazon-S3-Dienst',
    'The access secret for Amazon S3 service' => 'Das Zugriffsgeheimnis für den Amazon-S3-Dienst',
    'The region for Amazon S3 service' => 'Die Region für den Amazon-S3-Dienst',
    'Whether the customers can use this feature' => 'Ob die Kunden diese Funktion nutzen können',
    'Whether customer can use the system S3 account if they don\'t have their own account' => 'Ob Kunden das System-S3-Konto nutzen können, wenn sie kein eigenes Konto haben',
    'Whether customer can add their own S3 account' => 'Ob Kunden ihr eigenes S3-Konto hinzufügen können',
    'Whether the assets from email templates should be sent to Amazon S3 service' => 'Ob die Assets aus E-Mail-Vorlagen an den Amazon-S3-Dienst gesendet werden sollen',
    'The bucket name where the assets will be sent' => 'Der Bucket-Name, an den die Assets gesendet werden',
);
