<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "api" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Your IP address is not allowed to access this server.' => 'Ihre IP-Adresse darf nicht auf diesen Server zugreifen.',
    'Invalid API request params. Please refer to the documentation.' => 'Ungültige API-Anfrageparameter. Bitte schlagen Sie in der Dokumentation nach.',
    'Service Unavailable.' => 'Dienst nicht verfügbar.',
    'The subscribers list does not exist.' => 'Die Abonnentenliste existiert nicht.',
    'The subscribers list does not have any custom field defined.' => 'Die Abonnentenliste hat kein benutzerdefiniertes Feld definiert.',
    'The subscriber does not exist in this list.' => 'Der Abonnent existiert nicht in dieser Liste.',
    'Only POST requests allowed for this endpoint.' => 'Nur POST-Anfragen sind für diesen Endpunkt erlaubt.',
    'Please provide the subscriber email address.' => 'Bitte geben Sie die E-Mail-Adresse des Abonnenten an.',
    'Please provide a valid email address.' => 'Bitte geben Sie eine gültige E-Mail-Adresse an.',
    'The subscriber already exists in this list.' => 'Der Abonnent existiert bereits in dieser Liste.',
    'This email address is blacklisted.' => 'Diese E-Mail-Adresse steht auf der schwarzen Liste.',
    'The field {field} is required by the list but it has not been provided!' => 'Das Feld {field} wird von der Liste benötigt, wurde jedoch nicht bereitgestellt!',
    'Unable to save the subscriber!' => 'Der Abonnent konnte nicht gespeichert werden!',
    'Please provide the subscribers list.' => 'Bitte geben Sie die Abonnentenliste an.',
    'Only PUT requests allowed for this endpoint.' => 'Nur PUT-Anfragen sind für diesen Endpunkt erlaubt.',
    'Another subscriber with this email address already exists in this list.' => 'Ein anderer Abonnent mit dieser E-Mail-Adresse existiert bereits in dieser Liste.',
    'Only DELETE requests allowed for this endpoint.' => 'Nur DELETE-Anfragen sind für diesen Endpunkt erlaubt.',
    'The template does not exist.' => 'Die Vorlage existiert nicht.',
    'It does not seem that you have selected an archive.' => 'Es scheint, dass Sie kein Archiv ausgewählt haben.',
    'Your archive does not seem to be a valid zip file.' => 'Ihr Archiv scheint keine gültige ZIP-Datei zu sein.',
    'Cannot write archive in the temporary location.' => 'Das Archiv kann nicht im temporären Verzeichnis geschrieben werden.',
    'The list does not exist.' => 'Die Liste existiert nicht.',
    'You have reached the maximum number of allowed lists.' => 'Sie haben die maximale Anzahl erlaubter Listen erreicht.',
    'Unable to copy the list.' => 'Die Liste konnte nicht kopiert werden.',
    'The campaign does not exist.' => 'Die Kampagne existiert nicht.',
    'The subscriber does not exist.' => 'Der Abonnent existiert nicht.',
    'The url hash does not exist.' => 'Der URL-Hash existiert nicht.',
    'You have reached the maximum number of allowed campaigns.' => 'Sie haben die maximale Anzahl erlaubter Kampagnen erreicht.',
    'Please provide a list for this campaign.' => 'Bitte geben Sie eine Liste für diese Kampagne an.',
    'Provided list does not exist.' => 'Die angegebene Liste existiert nicht.',
    'Provided list segment does not exist.' => 'Das angegebene Listensegment existiert nicht.',
    'Provided template does not exist.' => 'Die angegebene Vorlage existiert nicht.',
    'Please provide a template for your campaign.' => 'Bitte geben Sie eine Vorlage für Ihre Kampagne an.',
    'Unable to copy the campaign.' => 'Die Kampagne konnte nicht kopiert werden.',
    'The campaign does not allow marking it as sent!' => 'Die Kampagne erlaubt es nicht, sie als gesendet zu markieren!',
    'This campaign cannot be removed now.' => 'Diese Kampagne kann jetzt nicht entfernt werden.',
    'The email does not exist.' => 'Die E-Mail existiert nicht.',
    'The campaign does not exist!' => 'Die Kampagne existiert nicht!',
    'The subscriber does not exist!' => 'Der Abonnent existiert nicht!',
    'This subscriber has already been marked as bounced!' => 'Dieser Abonnent wurde bereits als zurückgesprungen markiert!',
    'Invalid bounce type!' => 'Ungültiger Bounce-Typ!',
    'Customer creation is disabled.' => 'Die Erstellung von Kunden ist deaktiviert.',
    'Unable to find the specified country, please double check the spelling!' => 'Das angegebene Land konnte nicht gefunden werden, bitte überprüfen Sie die Schreibweise!',
    'Unable to find the specified zone, please double check the spelling!' => 'Die angegebene Zone konnte nicht gefunden werden, bitte überprüfen Sie die Schreibweise!',
);
