<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "app_monitor" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'CLI Monitor' => 'CLI-Monitor',
    'App Monitor' => 'App-Monitor',
    'Monitor Server IP' => 'Monitor-Server-IP',
    'Monitor Server port' => 'Monitor-Server-Port',
    'Monitor Server password' => 'Monitor-Server-Passwort',
    'The IP address of the Monitor Server' => 'Die IP-Adresse des Monitor-Servers',
    'The port of the Monitor Server' => 'Der Port des Monitor-Servers',
    'The password for the Monitor Server' => 'Das Passwort für den Monitor-Server',
);
