<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "articles" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'View article categories' => 'Artikelkategorien anzeigen',
    'Articles' => 'Artikel',
    'Categories' => 'Kategorien',
    'Create new article category' => 'Neue Artikelkategorie erstellen',
    'Update article category' => 'Artikelkategorie aktualisieren',
    'View zones' => 'Zonen anzeigen',
    'View countries' => 'Länder anzeigen',
    'View articles' => 'Artikel anzeigen',
    'Create new article' => 'Neuen Artikel erstellen',
    'Update article' => 'Artikel aktualisieren',
    'Category' => 'Kategorie',
    'Parent' => 'Übergeordnet',
    'Name' => 'Name',
    'Slug' => 'Slug',
    'Description' => 'Beschreibung',
    'My category name' => 'Mein Kategoriename',
    'my-category-name' => 'mein-kategoriename',
    'Article' => 'Artikel',
    'Title' => 'Titel',
    'Content' => 'Inhalt',
    'Published' => 'Veröffentlicht',
    'Unpublished' => 'Unveröffentlicht',
    'My article title' => 'Mein Artikeltitel',
    'my-article-title' => 'mein-artikeltitel',
    'Related articles' => 'Verwandte Artikel',
    'Helpful articles' => 'Hilfreiche Artikel',
    'This article is unpublished, only site admins can see it!' => 'Dieser Artikel ist unveröffentlicht, nur Seitenadministratoren können ihn sehen!',
    'All articles filled in under this category' => 'Alle Artikel, die unter dieser Kategorie eingeordnet sind',
    'We\'re sorry, but this category doesn\'t have any published article yet!' => 'Entschuldigung, aber diese Kategorie hat noch keine veröffentlichten Artikel!',
    'List of helpful articles' => 'Liste hilfreicher Artikel',
    'We\'re sorry, but for now there is no published article!' => 'Entschuldigung, aber derzeit gibt es keine veröffentlichten Artikel!',
);
