<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "campaign_activity_map" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Show opens map' => 'Karte der Öffnungen anzeigen',
    'Show clicks map' => 'Karte der Klicks anzeigen',
    'Opens at once' => 'Öffnungen auf einmal',
    'Clicks at once' => 'Klicks auf einmal',
    'Show unsubscribes map' => 'Karte der Abmeldungen anzeigen',
    'Unsubscribes at once' => 'Abmeldungen auf einmal',
    'Google maps API key' => 'Google Maps API-Schlüssel',
    'Whether to show a map with location opens in campaign overview' => 'Ob eine Karte mit den Standorten der Öffnungen in der Kampagnenübersicht angezeigt werden soll',
    'Whether to show a map with location clicks in campaign overview' => 'Ob eine Karte mit den Standorten der Klicks in der Kampagnenübersicht angezeigt werden soll',
    'How many open records to load at once per ajax call? More records means more memory usage' => 'Wie viele Öffnungsdatensätze sollen pro Ajax-Aufruf auf einmal geladen werden? Mehr Datensätze bedeuten mehr Speicherverbrauch',
    'How many click records to load at once per ajax call? More records means more memory usage' => 'Wie viele Klickdatensätze sollen pro Ajax-Aufruf auf einmal geladen werden? Mehr Datensätze bedeuten mehr Speicherverbrauch',
    'Whether to show a map with location from where subscribers unsubscribed in campaign overview' => 'Ob eine Karte mit den Standorten angezeigt werden soll, von denen sich Abonnenten in der Kampagnenübersicht abgemeldet haben',
    'How many unsubscribe records to load at once per ajax call? More records means more memory usage' => 'Wie viele Abmeldedatensätze sollen pro Ajax-Aufruf auf einmal geladen werden? Mehr Datensätze bedeuten mehr Speicherverbrauch',
    'Your google maps API key. It is optional but needed if you go over the free quota assigned by Google' => 'Ihr Google Maps API-Schlüssel. Er ist optional, aber erforderlich, wenn Sie das von Google zugewiesene kostenlose Kontingent überschreiten',
    'Campaign activity map' => 'Kampagnenaktivitätskarte',
    'Decide whether to show various maps in the campaign overview area.' => 'Entscheiden Sie, ob verschiedene Karten im Bereich der Kampagnenübersicht angezeigt werden sollen.',
);
