<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "ckeditor" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Enable filemanager for users' => 'Enable filemanager for users',
  'Enable filemanager for customers' => 'Enable filemanager for customers',
  'Default toolbar' => 'Default toolbar',
  'Filemanager theme' => 'Filemanager theme',
  'Whether to enable the filemanager for users' => 'Whether to enable the filemanager for users',
  'Whether to enable the filemanager for customers' => 'Whether to enable the filemanager for customers',
  'Default toolbar for all editor instances' => 'Default toolbar for all editor instances',
  'The file manager theme' => 'The file manager theme',
  'CKeditor options' => 'CKeditor options',
  'Filemanager' => 'Filemanager',
  'File manager' => 'File manager',
  'Enable the editor' => 'Enable the editor',
  'File manager theme' => 'File manager theme',
  'Whether to enable the editor' => 'Whether to enable the editor',
);
