<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "ckeditor" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Aktivieren Sie den Dateimanager für Benutzer' => 'Aktivieren Sie den Dateimanager für Benutzer',
    'Aktivieren Sie den Dateimanager für Kunden' => 'Aktivieren Sie den Dateimanager für Kunden',
    'Standard-Symbolleiste' => 'Standard-Symbolleiste',
    'Dateimanager-Design' => 'Dateimanager-Design',
    'Ob der Dateimanager für Benutzer aktiviert werden soll' => 'Ob der Dateimanager für Benutzer aktiviert werden soll',
    'Ob der Dateimanager für Kunden aktiviert werden soll' => 'Ob der Dateimanager für Kunden aktiviert werden soll',
    'Standard-Symbolleiste für alle Editorinstanzen' => 'Standard-Symbolleiste für alle Editorinstanzen',
    'Das Design des Dateimanagers' => 'Das Design des Dateimanagers',
    'CKeditor-Optionen' => 'CKeditor-Optionen',
    'Dateimanager' => 'Dateimanager',
    'Datei-Manager' => 'Datei-Manager',
    'Editor aktivieren' => 'Editor aktivieren',
    'Datei-Manager-Design' => 'Datei-Manager-Design',
    'Ob der Editor aktiviert werden soll' => 'Ob der Editor aktiviert werden soll',
);
