<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "common_email_templates" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'View email templates' => 'E-Mail-Vorlagen anzeigen',
    'Common email templates' => 'Allgemeine E-Mail-Vorlagen',
    'Create new template' => 'Neue Vorlage erstellen',
    'Update template' => 'Vorlage aktualisieren',
    'This will delete the core email templates and will reinstall them based on the common template. Are you sure you want to continue?' => 'Dies wird die Kern-E-Mail-Vorlagen löschen und basierend auf der allgemeinen Vorlage neu installieren. Sind Sie sicher, dass Sie fortfahren möchten?',
    'Reinstall core templates' => 'Kernvorlagen neu installieren',
    'Available tags' => 'Verfügbare Tags',
    'Tag' => 'Tag',
    'Description' => 'Beschreibung',
    'Template' => 'Vorlage',
    'Name' => 'Name',
    'Slug' => 'Slug',
    'Subject' => 'Betreff',
    'Content' => 'Inhalt',
    'The name of the template, used internally mostly' => 'Der Name der Vorlage, hauptsächlich intern verwendet',
    'The subject which will be used for this email' => 'Der Betreff, der für diese E-Mail verwendet wird',
    'The email content' => 'Der E-Mail-Inhalt',
    'Shows the current date' => 'Zeigt das aktuelle Datum an',
    'Shows the current year' => 'Zeigt das aktuelle Jahr an',
    'Shows the current month' => 'Zeigt den aktuellen Monat an',
    'Shows the current day' => 'Zeigt den aktuellen Tag an',
    'Shows the site name' => 'Zeigt den Namen der Website an',
);
