<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "common_email_templates" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View email templates' => 'View email templates',
  'Common email templates' => 'Common email templates',
  'Create new template' => 'Create new template',
  'Update template' => 'Update template',
  'This will delete the core email templates and will reinstall them based on the common template. Are you sure you want to continue?' => 'This will delete the core email templates and will reinstall them based on the common template. Are you sure you want to continue?',
  'Reinstall core templates' => 'Reinstall core templates',
  'Available tags' => 'Available tags',
  'Tag' => 'Tag',
  'Description' => 'Description',
  'Template' => 'Template',
  'Name' => 'Name',
  'Slug' => 'Slug',
  'Subject' => 'Subject',
  'Content' => 'Content',
  'The name of the template, used internally mostly' => 'The name of the template, used internally mostly',
  'The subject which will be used for this email' => 'The subject which will be used for this email',
  'The email content' => 'The email content',
  'Shows the current date' => 'Shows the current date',
  'Shows the current year' => 'Shows the current year',
  'Shows the current month' => 'Shows the current month',
  'Shows the current day' => 'Shows the current day',
  'Shows the site name' => 'Shows the site name',
);
