<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "console" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'ID' => 'ID',
  'Command' => 'Command',
  'Action' => 'Action',
  'Params' => 'Params',
  'Start time' => 'Start time',
  'End time' => 'End time',
  'Start memory' => 'Start memory',
  'End memory' => 'End memory',
  'Duration' => 'Duration',
  'Memory usage' => 'Memory usage',
  'seconds' => 'seconds',
);
