<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "cookie_consent" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Cookie consent' => 'Cookie consent',
  'Bottom' => 'Bottom',
  'Bottom left' => 'Bottom left',
  'Bottom right' => 'Bottom right',
  'Top' => 'Top',
  'Top left' => 'Top left',
  'Top right' => 'Top right',
  'Message' => 'Message',
  'Position' => 'Position',
  'Theme' => 'Theme',
  'Banner background color' => 'Banner background color',
  'Button color' => 'Button color',
  'This website uses cookies to improve your experience.' => 'This website uses cookies to improve your experience.',
  'The message that will appear on your cookie consent banner' => 'The message that will appear on your cookie consent banner',
  'Where the cookie consent banner will appear' => 'Where the cookie consent banner will appear',
  'The theme of the cookie consent banner' => 'The theme of the cookie consent banner',
  'Select background color' => 'Select background color',
  'Reset background color' => 'Reset background color',
  'Select button color' => 'Select button color',
  'Reset button color' => 'Reset button color',
);
