<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "countries" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View countries' => 'View countries',
  'Countries' => 'Countries',
  'Create new country' => 'Create new country',
  'Update country' => 'Update country',
  'Confirm country removal' => 'Confirm country removal',
  'Please note that removing this country will also remove every record that depends on it, such as zones, taxes, customer companies, etc!' => 'Please note that removing this country will also remove every record that depends on it, such as zones, taxes, customer companies, etc!',
  'Are you still sure you want to remove this country? There is no coming back after you do it!' => 'Are you still sure you want to remove this country? There is no coming back after you do it!',
  'Country' => 'Country',
  'Name' => 'Name',
  'Code' => 'Code',
);
