<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "cronjobs" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View cron jobs list' => 'View cron jobs list',
  'Cron jobs list' => 'Cron jobs list',
  'View cron jobs history' => 'View cron jobs history',
  'Cron jobs history' => 'Cron jobs history',
  'Showing various info about all the cron jobs that run for the application. We keep latest 10 records in the history for each cron job that runs.' => 'Showing various info about all the cron jobs that run for the application. We keep latest 10 records in the history for each cron job that runs.',
  'Application cron jobs' => 'Application cron jobs',
  'Description' => 'Description',
  'Cronjob' => 'Cronjob',
  'Please note that all the cron jobs below must be added on your server in order for the application to work properly.' => 'Please note that all the cron jobs below must be added on your server in order for the application to work properly.',
  'Please consult your web hosting knowledge base in order to understand how these cron jobs must be added on your server.' => 'Please consult your web hosting knowledge base in order to understand how these cron jobs must be added on your server.',
);
