<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "cron_jobs" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Campaigns sender, runs each minute.' => 'Campaigns sender, runs each minute.',
  'Queue handler, runs each minute.' => 'Queue handler, runs each minute.',
  'Transactional email sender, runs once at 2 minutes.' => 'Transactional email sender, runs once at 2 minutes.',
  'Bounce handler, runs once at 10 minutes.' => 'Bounce handler, runs once at 10 minutes.',
  'Feedback loop handler, runs once at 20 minutes.' => 'Feedback loop handler, runs once at 20 minutes.',
  'Delivery/Bounce processor, runs once at 3 minutes.' => 'Delivery/Bounce processor, runs once at 3 minutes.',
  'Various tasks, runs each hour.' => 'Various tasks, runs each hour.',
  'Daily cleaner, runs once a day.' => 'Daily cleaner, runs once a day.',
);
