<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "custom_subscriber_attachment" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Custom subscriber attachment' => 'Custom subscriber attachment',
  'Common' => 'Common',
  'You have to set the absolute path to the storage folder where you will upload attachments. By default it is: {path}' => 'You have to set the absolute path to the storage folder where you will upload attachments. By default it is: {path}',
  'After you set the storage folder, inside it, you can upload your subscriber specific attachments but make sure you create subfolders and you upload the attachments in these subfolders.' => 'After you set the storage folder, inside it, you can upload your subscriber specific attachments but make sure you create subfolders and you upload the attachments in these subfolders.',
  'For example, you can have following structure:' => 'For example, you can have following structure:',
  'Then in the campaign setup step, you will be able to select the "{folder}" folder as the folder from where the attachments will be loaded. Also, you will be able to select which custom field represents the file name.' => 'Then in the campaign setup step, you will be able to select the "{folder}" folder as the folder from where the attachments will be loaded. Also, you will be able to select which custom field represents the file name.',
  'Storage folder' => 'Storage folder',
  'The storage folder where the attachment folders will be created' => 'The storage folder where the attachment folders will be created',
);
