<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "dashboard" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Dashboard' => 'Dashboard',
  'Are you sure you want to remove all blacklisted emails?' => 'Are you sure you want to remove all blacklisted emails?',
  'Are you sure you want to remove all login logs?' => 'Are you sure you want to remove all login logs?',
  'Are you sure you want to remove all blacklist monitors?' => 'Are you sure you want to remove all blacklist monitors?',
  'Recent activity' => 'Recent activity',
  'Customers' => 'Customers',
  'Campaigns' => 'Campaigns',
  'Lists' => 'Lists',
  'Subscribers' => 'Subscribers',
  'Segments' => 'Segments',
  'Delivery servers' => 'Delivery servers',
  'Templates' => 'Templates',
  'Are you sure you want to remove all suppressed emails?' => 'Are you sure you want to remove all suppressed emails?',
  'Are you sure you want to remove all suppressed IPs?' => 'Are you sure you want to remove all suppressed IPs?',
);
