<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "dashboard" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Dashboard' => 'Dashboard',
  'Are you sure you want to remove all blacklisted emails?' => 'Sind Sie sicher, dass Sie alle blockierten E-Mails entfernen möchten?',
  'Are you sure you want to remove all login logs?' => 'Sind Sie sicher, dass Sie alle Anmeldeprotokolle entfernen möchten?',
  'Are you sure you want to remove all blacklist monitors?' => 'Sind Sie sicher, dass Sie alle Blacklist-Überwachungen entfernen möchten?',
  'Recent activity' => 'Letzte Aktivitäten',
  'Customers' => 'Kunden',
  'Campaigns' => 'Kampagnen',
  'Lists' => 'Listen',
  'Subscribers' => 'Abonnenten',
  'Segments' => 'Segmente',
  'Delivery servers' => 'Versandserver',
  'Templates' => 'Vorlagen',
  'Are you sure you want to remove all suppressed emails?' => 'Sind Sie sicher, dass Sie alle unterdrückten E-Mails entfernen möchten?',
  'Are you sure you want to remove all suppressed IPs?' => 'Sind Sie sicher, dass Sie alle unterdrückten IPs entfernen möchten?',
);
