<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "domain_blacklist" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View domains blacklist' => 'View domains blacklist',
  'Domains blacklist' => 'Domains blacklist',
  'Domain' => 'Domain',
  'Blacklist domains allows you to blacklist emails that belongs to a certain domain/subdomain.' => 'Blacklist domains allows you to blacklist emails that belongs to a certain domain/subdomain.',
  'Import from CSV file' => 'Import from CSV file',
  'If unsure about how to format your file, do an export first and see how the file looks.' => 'If unsure about how to format your file, do an export first and see how the file looks.',
);
