<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "email_verification" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Email verification' => 'Email verification',
  'Email verification provider providers' => 'Email verification provider providers',
  'Email verification providers' => 'Email verification providers',
  'Check email address validity using Emailable service.' => 'Check email address validity using Emailable service.',
  'Name' => 'Name',
  'Description' => 'Description',
  'Enabled' => 'Enabled',
  'Email List Verify' => 'Email List Verify',
  'Api key' => 'Api key',
  'Api url' => 'Api url',
  'Customer groups' => 'Customer groups',
  'Check zones' => 'Check zones',
  'The api key for the service' => 'The api key for the service',
  'The api url for the service' => 'The api url for the service',
  'Decide which customer groups can make use of this extension. If no group is selected, then all customers can use it. Please note that customers must use their own service credentials to validate the emails.' => 'Decide which customer groups can make use of this extension. If no group is selected, then all customers can use it. Please note that customers must use their own service credentials to validate the emails.',
  'Select the zones where email validation will run. If no zone is selected, then validation will run everywhere.' => 'Select the zones where email validation will run. If no zone is selected, then validation will run everywhere.',
  '{service} is a email validation service that helps detecting bad email addresses.' => '{service} is a email validation service that helps detecting bad email addresses.',
  'If you enable this extension, your customers will be able to use their own Email List Verify info for validating their own emails.' => 'If you enable this extension, your customers will be able to use their own Email List Verify info for validating their own emails.',
  'Zerobounce' => 'Zerobounce',
  'If you enable this extension, your customers will be able to use their own Zerobounce info for validating their own emails.' => 'If you enable this extension, your customers will be able to use their own Zerobounce info for validating their own emails.',
  'Kickbox' => 'Kickbox',
  'If you enable this extension, your customers will be able to use their own Kickbox info for validating their own emails.' => 'If you enable this extension, your customers will be able to use their own Kickbox info for validating their own emails.',
  'Everifier.org' => 'Everifier.org',
  'If you enable this extension, your customers will be able to use their own Everifier.org info for validating their own emails.' => 'If you enable this extension, your customers will be able to use their own Everifier.org info for validating their own emails.',
  'Bulk Email Checker' => 'Bulk Email Checker',
  'If you enable this extension, your customers will be able to use their own Bulk Email Checker info for validating their own emails.' => 'If you enable this extension, your customers will be able to use their own Bulk Email Checker info for validating their own emails.',
  'Emailable' => 'Emailable',
  'If you enable this extension, your customers will be able to use their own Emailable info for validating their own emails.' => 'If you enable this extension, your customers will be able to use their own Emailable info for validating their own emails.',
  'Campaign Sending' => 'Campaign Sending',
  'List Import' => 'List Import',
  'List Subscribe' => 'List Subscribe',
  'List Export' => 'List Export',
  'Transactional Emails Sending' => 'Transactional Emails Sending',
  'You can enable the service, insert your details, then decide when exactly you want to run the email validation.' => 'You can enable the service, insert your details, then decide when exactly you want to run the email validation.',
);
