<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "email_template_builder" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Toggle template builder' => 'Toggle template builder',
  'The template you create with the builder must be modified only using the builder.' => 'The template you create with the builder must be modified only using the builder.',
  'Do not modify the template outside the builder, it will break.' => 'Do not modify the template outside the builder, it will break.',
  'Email template builder' => 'Email template builder',
  ' Current builder' => ' Current builder',
  'Please select the builder that you want to use' => 'Please select the builder that you want to use',
  'Stripo settings' => 'Stripo settings',
  'Plugin ID' => 'Plugin ID',
  'Secret Key' => 'Secret Key',
  'Your Stripo Plugin ID' => 'Your Stripo Plugin ID',
  'Your Stripo Secret Key' => 'Your Stripo Secret Key',
  'Toggle {name} template builder' => 'Toggle {name} template builder',
  'Are you sure you want to load the default template? All your previous work will be lost.' => 'Are you sure you want to load the default template? All your previous work will be lost.',
  'Load default template' => 'Load default template',
);
