<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "email_templates" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Email templates' => 'Email templates',
  'View templates' => 'View templates',
  'Gallery' => 'Gallery',
  'You successfully created a new email template!' => 'You successfully created a new email template!',
  'Create email template' => 'Create email template',
  'You successfully updated your email template!' => 'You successfully updated your email template!',
  'Update email template' => 'Update email template',
  'Unable to copy the template!' => 'Unable to copy the template!',
  'The template has been successfully copied!' => 'The template has been successfully copied!',
  'Please wait while saving your template screenshot...' => 'Please wait while saving your template screenshot...',
  'Your template was successfully deleted!' => 'Your template was successfully deleted!',
  'View categories' => 'View categories',
  'Categories' => 'Categories',
  'Create new category' => 'Create new category',
  'Update category' => 'Update category',
  'Upload template' => 'Upload template',
  'Preview' => 'Preview',
  'Upload template archive' => 'Upload template archive',
  'Upload archive' => 'Upload archive',
  'Category' => 'Category',
  'Customer' => 'Customer',
  'Name' => 'Name',
  'Templates' => 'Templates',
  'Template' => 'Template',
  'Template uid' => 'Template uid',
  'Content' => 'Content',
  'Content hash' => 'Content hash',
  'Create screenshot' => 'Create screenshot',
  'Screenshot' => 'Screenshot',
  'Archive file' => 'Archive file',
  'The name of the template, used for you to make the difference if having to many templates.' => 'The name of the template, used for you to make the difference if having to many templates.',
  'Email templates gallery' => 'Email templates gallery',
  'Unable to import the template!' => 'Unable to import the template!',
  'Unable to save the imported template!' => 'Unable to save the imported template!',
  'The template has been successfully imported!' => 'The template has been successfully imported!',
  'Please specify the email address to where we should send the test email.' => 'Please specify the email address to where we should send the test email.',
  'Email delivery is temporary disabled.' => 'Email delivery is temporary disabled.',
  'The email address {email} does not seem to be valid!' => 'The email address {email} does not seem to be valid!',
  'Cannot send using provided email address(es)!' => 'Cannot send using provided email address(es)!',
  'Unable to send the test email to {email}!' => 'Unable to send the test email to {email}!',
  'Test email successfully sent to {email}!' => 'Test email successfully sent to {email}!',
  'Send a test email using this template' => 'Send a test email using this template',
  'Send a test email' => 'Send a test email',
  'Send test' => 'Send test',
  'Import html from url' => 'Import html from url',
  'Import html template from url' => 'Import html template from url',
  'Please note that your url must contain a valid html email template with absolute paths to resources!' => 'Please note that your url must contain a valid html email template with absolute paths to resources!',
  'Import' => 'Import',
  'Please see <a href="{templateArchiveHref}">this example archive</a> in order to understand how you should format your uploaded archive! Also, please note we only accept zip files.' => 'Please see <a href="{templateArchiveHref}">this example archive</a> in order to understand how you should format your uploaded archive! Also, please note we only accept zip files.',
  '* if multiple recipients, separate the email addresses by a comma.<br /> * the email tags will not be parsed while sending test emails.<br /> * make sure you save the template changes before you send the test.' => '* if multiple recipients, separate the email addresses by a comma.<br /> * the email tags will not be parsed while sending test emails.<br /> * make sure you save the template changes before you send the test.',
);
