<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "favorite_pages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Favorite pages' => 'Favorite pages',
  'Are you sure you want to {action} favorites?' => 'Are you sure you want to {action} favorites?',
  'Please click here to {action} favorites' => 'Please click here to {action} favorites',
  'Page' => 'Page',
  'Customer' => 'Customer',
  'User' => 'User',
  'Label' => 'Label',
  'Route' => 'Route',
  'Route params' => 'Route params',
  'Route hash' => 'Route hash',
  'Clicks count' => 'Clicks count',
  'Reset the clicks counter' => 'Reset the clicks counter',
  'The page has been added to favorites successfully' => 'The page has been added to favorites successfully',
  'Are you sure you want to remove this page from favorites?' => 'Are you sure you want to remove this page from favorites?',
  'Please click here to remove this page from favorites' => 'Please click here to remove this page from favorites',
  'The page has been removed from favorites' => 'The page has been removed from favorites',
  'Are you sure you want to add this page to favorites?' => 'Are you sure you want to add this page to favorites?',
  'Please click here to add this page to favorites' => 'Please click here to add this page to favorites',
);
