<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "ip_blacklist" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'IP address' => 'IP-Adresse',
  'Customer' => 'Kunde',
  'Import from CSV file' => 'Aus CSV-Datei importieren',
  'Please note, the csv file must contain a header with at least the ip_address column.' => 'Bitte beachten Sie, dass die CSV-Datei eine Kopfzeile mit mindestens der Spalte ip_address enthalten muss.',
  'Add a new IP to blacklist' => 'Neue IP zur Blacklist hinzufügen',
  'Please enter a valid IP address!' => 'Bitte geben Sie eine gültige IP-Adresse ein!',
  'Update blacklisted IP' => 'Schwarze Liste IP aktualisieren',
);
