<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "ip_blacklist" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'IP address' => 'IP address',
  'Customer' => 'Customer',
  'Import from CSV file' => 'Import from CSV file',
  'Please note, the csv file must contain a header with at least the ip_address column.' => 'Please note, the csv file must contain a header with at least the ip_address column.',
  'Add a new IP to blacklist' => 'Add a new IP to blacklist',
  'Please enter a valid IP address!' => 'Please enter a valid IP address!',
  'Update blacklisted IP' => 'Update blacklisted IP',
);
