<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "ip_location" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Ip location services' => 'Ip location services',
  'MaxMind.com database' => 'MaxMind.com database',
  'Name' => 'Name',
  'Description' => 'Description',
  'Status' => 'Status',
  'Sort order' => 'Sort order',
  'Service detail page' => 'Service detail page',
  'Ip location services are used to collect location data(country, zone, city) when subscribers open the email campaigns or when they click on a trackable url, etc.' => 'Ip location services are used to collect location data(country, zone, city) when subscribers open the email campaigns or when they click on a trackable url, etc.',
  'This data is then used in campaign reports to show you the exact location where the email campaign has been opened or the location from where the subscriber clicked a link from within the campaign.' => 'This data is then used in campaign reports to show you the exact location where the email campaign has been opened or the location from where the subscriber clicked a link from within the campaign.',
  'Please note, data accuracy will vary between the services. You should test the service website before enable.' => 'Please note, data accuracy will vary between the services. You should test the service website before enable.',
  'Path on server' => 'Path on server',
  'Download' => 'Download',
  'Action to take' => 'Action to take',
  'Download and place it in the right path' => 'Download and place it in the right path',
  'None' => 'None',
  'This product includes GeoLite2 data created by MaxMind, available from {from}' => 'This product includes GeoLite2 data created by MaxMind, available from {from}',
  'Location' => 'Location',
  'Ip address' => 'Ip address',
  'Country code' => 'Country code',
  'Country name' => 'Country name',
  'Zone name' => 'Zone name',
  'City name' => 'City name',
  'Latitude' => 'Latitude',
  'Longitude' => 'Longitude',
  'Timezone' => 'Timezone',
  'The database file which should be located at "{path}" is missing!' => 'The database file which should be located at "{path}" is missing!',
  'Please download latest version from {link}, decompress it and place the resulted .mmdb file to be accessible at the above path!' => 'Please download latest version from {link}, decompress it and place the resulted .mmdb file to be accessible at the above path!',
  'Maxmind\'s site' => 'Maxmind\'s site',
);
