<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "languages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View available languages' => 'Verfügbare Sprachen anzeigen',
  'Languages' => 'Sprachen',
  'Create new language' => 'Neue Sprache erstellen',
  'Update language' => 'Sprache aktualisieren',
  'Your language pack has been successfully uploaded!' => 'Ihr Sprachpaket wurde erfolgreich hochgeladen!',
  'Please select a language pack archive for upload!' => 'Bitte wählen Sie ein Sprachpaket-Archiv zum Hochladen aus!',
  'Upload language pack' => 'Sprachpaket hochladen',
  'Please note that only zip files are allowed for upload.' => 'Bitte beachten Sie, dass nur ZIP-Dateien hochgeladen werden dürfen.',
  'Language packs contain executable PHP files, please check the packs before upload.' => 'Sprachpakete enthalten ausführbare PHP-Dateien, bitte überprüfen Sie die Pakete vor dem Hochladen.',
  'Language' => 'Sprache',
  'Name' => 'Name',
  'Language code' => 'Sprachcode',
  'Region code' => 'Regionscode',
  'Is default language?' => 'Ist Standardsprache?',
  'The visible language name to distinct between same language but distinct regions (i.e: between English US and English GB)' => 'Der sichtbare Sprachname zur Unterscheidung zwischen derselben Sprache, aber unterschiedlichen Regionen (z. B.: zwischen Englisch US und Englisch GB)',
  '2 letter language code, i.e: en' => '2-Buchstaben-Sprachcode, z. B.: en',
  '2 letter region code, i.e: us. Please do not fill this field unless necessary. For most of the cases, the language code is enough' => '2-Buchstaben-Regionscode, z. B.: us. Bitte füllen Sie dieses Feld nur aus, wenn es notwendig ist. In den meisten Fällen reicht der Sprachcode aus',
  'Whether this language is the default language for users/customers that have not set a language' => 'Ob diese Sprache die Standardsprache für Benutzer/Kunden ist, die keine Sprache festgelegt haben',
  'i.e: English - United States' => 'z. B.: Englisch - Vereinigte Staaten',
  'i.e: en' => 'z. B.: en',
  'i.e: us' => 'z. B.: us',
  'The archive upload is only allowed for php message source.' => 'Das Hochladen von Archiven ist nur für PHP-Nachrichtenquellen erlaubt.',
  'The language directory {dirName} is not valid and was deleted!' => 'Das Sprachverzeichnis {dirName} ist ungültig und wurde gelöscht!',
  'The language "{languageName}" cannot be saved, failure reason: ' => 'Die Sprache "{languageName}" kann nicht gespeichert werden, Fehlergrund: ',
  'Duplicate entry for the language and region code combination!' => 'Doppelter Eintrag für die Kombination aus Sprach- und Regionscode!',
);
