<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "languages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View available languages' => 'View available languages',
  'Languages' => 'Languages',
  'Create new language' => 'Create new language',
  'Update language' => 'Update language',
  'Your language pack has been successfully uploaded!' => 'Your language pack has been successfully uploaded!',
  'Please select a language pack archive for upload!' => 'Please select a language pack archive for upload!',
  'Upload language pack' => 'Upload language pack',
  'Please note that only zip files are allowed for upload.' => 'Please note that only zip files are allowed for upload.',
  'Language packs contain executable PHP files, please check the packs before upload.' => 'Language packs contain executable PHP files, please check the packs before upload.',
  'Language' => 'Language',
  'Name' => 'Name',
  'Language code' => 'Language code',
  'Region code' => 'Region code',
  'Is default language?' => 'Is default language?',
  'The visible language name to distinct between same language but distinct regions (i.e: between English US and English GB)' => 'The visible language name to distinct between same language but distinct regions (i.e: between English US and English GB)',
  '2 letter language code, i.e: en' => '2 letter language code, i.e: en',
  '2 letter region code, i.e: us. Please do not fill this field unless necessary. For most of the cases, the language code is enough' => '2 letter region code, i.e: us. Please do not fill this field unless necessary. For most of the cases, the language code is enough',
  'Whether this language is the default language for users/customers that have not set a language' => 'Whether this language is the default language for users/customers that have not set a language',
  'i.e: English - United States' => 'i.e: English - United States',
  'i.e: en' => 'i.e: en',
  'i.e: us' => 'i.e: us',
  'The archive upload is only allowed for php message source.' => 'The archive upload is only allowed for php message source.',
  'The language directory {dirName} is not valid and was deleted!' => 'The language directory {dirName} is not valid and was deleted!',
  'The language "{languageName}" cannot be saved, failure reason: ' => 'The language "{languageName}" cannot be saved, failure reason: ',
  'Duplicate entry for the language and region code combination!' => 'Duplicate entry for the language and region code combination!',
);
