<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "list_segments" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Segments' => 'Segments',
  'Segment' => 'Segment',
  'List' => 'List',
  'Name' => 'Name',
  'Operator match' => 'Operator match',
  'Subscribers count' => 'Subscribers count',
  'Condition' => 'Condition',
  'Operator' => 'Operator',
  'Field' => 'Field',
  'Value' => 'Value',
  'It will be transformed into an empty value' => 'It will be transformed into an empty value',
  'It will be transformed into the current date/time in the format of Y-m-d H:i:s (i.e: {datetime})' => 'It will be transformed into the current date/time in the format of Y-m-d H:i:s (i.e: {datetime})',
  'It will be transformed into the current date in the format of Y-m-d (i.e: {date})' => 'It will be transformed into the current date in the format of Y-m-d (i.e: {date})',
  'It will rewind the current date by X days and use that as a comparison date' => 'It will rewind the current date by X days and use that as a comparison date',
  'It will forward the current date by X days and use that as a comparison date' => 'It will forward the current date by X days and use that as a comparison date',
  'It requires the birthday custom field value to be in the format of Y-m-d (i.e: {date}) in order to work properly' => 'It requires the birthday custom field value to be in the format of Y-m-d (i.e: {date}) in order to work properly',
  'It will forward the birthday by X days relative to the current date and use that as a comparison date.' => 'It will forward the birthday by X days relative to the current date and use that as a comparison date.',
  'List segments' => 'List segments',
  'Your mail list segments' => 'Your mail list segments',
  ' List segments' => ' List segments',
  'You are only allowed to add {num} segment conditions.' => 'You are only allowed to add {num} segment conditions.',
  'Current segmentation is too deep and loads too slow, please revise your segment conditions!' => 'Current segmentation is too deep and loads too slow, please revise your segment conditions!',
  'Create a new list segment' => 'Create a new list segment',
  'Update list segment' => 'Update list segment',
  'Your list segment was successfully copied!' => 'Your list segment was successfully copied!',
  'This segment contains {count} subscribers' => 'This segment contains {count} subscribers',
  'Sorry, but there are no subscribers matching your segment.' => 'Sorry, but there are no subscribers matching your segment.',
  'Defined conditions:' => 'Defined conditions:',
  'Subscribers matching your segment:' => 'Subscribers matching your segment:',
  'Available value tags' => 'Available value tags',
  'Following tags can be used as dynamic values. They will be replaced as shown below.' => 'Following tags can be used as dynamic values. They will be replaced as shown below.',
  'Tag' => 'Tag',
  'Description' => 'Description',
  'any' => 'any',
  'all' => 'all',
  'Conditions that apply to your list custom fields:' => 'Conditions that apply to your list custom fields:',
  'Conditions that apply to the campaigns sent to the list this segment belongs to:' => 'Conditions that apply to the campaigns sent to the list this segment belongs to:',
  'is' => 'is',
  'is not' => 'is not',
  'contains' => 'contains',
  'not contains' => 'not contains',
  'starts with' => 'starts with',
  'ends with' => 'ends with',
  'is greater than' => 'is greater than',
  'is less than' => 'is less than',
  'not starts with' => 'not starts with',
  'not ends with' => 'not ends with',
  'Open' => 'Open',
  'Click' => 'Click',
  'Day(s)' => 'Day(s)',
  'Month(s)' => 'Month(s)',
  'Year(s)' => 'Year(s)',
  'Less then or equal' => 'Less then or equal',
  'Less then' => 'Less then',
  'Greater than or equal' => 'Greater than or equal',
  'Greater than' => 'Greater than',
  'Equal' => 'Equal',
  'Campaign' => 'Campaign',
  'Campaign action' => 'Campaign action',
  'Click url' => 'Click url',
  'Time value' => 'Time value',
  'Time unit' => 'Time unit',
  'Comparison' => 'Comparison',
  'Any list campaign' => 'Any list campaign',
  'A new segment called "{segmentName}" has been added to the list "{listName}" successfully!' => 'A new segment called "{segmentName}" has been added to the list "{listName}" successfully!',
  'The segment called "{segmentName}" belonging to the list "{listName}" has been successfully updated!' => 'The segment called "{segmentName}" belonging to the list "{listName}" has been successfully updated!',
  'The segment {segmentName} belonging to the list "{listName}" has been successfully deleted!' => 'The segment {segmentName} belonging to the list "{listName}" has been successfully deleted!',
  'Not Open' => 'Not Open',
  'Not Click' => 'Not Click',
  'View archived segments' => 'View archived segments',
  'View all list segments' => 'View all list segments',
  'Your list segment was successfully archived!' => 'Your list segment was successfully archived!',
  'Your list segment was successfully unarchived!' => 'Your list segment was successfully unarchived!',
  'Archived segments' => 'Archived segments',
  'It will rewind the current date/time by X hours and use that as a comparison' => 'It will rewind the current date/time by X hours and use that as a comparison',
  'It will forward the current date/time by X hours and use that as a comparison' => 'It will forward the current date/time by X hours and use that as a comparison',
  'It will rewind the current date/time by X minutes and use that as a comparison' => 'It will rewind the current date/time by X minutes and use that as a comparison',
  'It will forward the current date/time by X minutes and use that as a comparison' => 'It will forward the current date/time by X minutes and use that as a comparison',
);
