<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "list_pages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Pages' => 'Pages',
  'List' => 'List',
  'Type' => 'Type',
  'Content' => 'Content',
  'Email subject' => 'Email subject',
  'The following tag is required but was not found in your content: {tag}' => 'The following tag is required but was not found in your content: {tag}',
  'List pages' => 'List pages',
  'Select another list page to edit' => 'Select another list page to edit',
  'Your unsubscribe form url is:' => 'Your unsubscribe form url is:',
  'Preview it now!' => 'Preview it now!',
  'Your subscribe form url is:' => 'Your subscribe form url is:',
  'Subscribe form' => 'Subscribe form',
  'Pending subscribe' => 'Pending subscribe',
  'Subscription confirmed' => 'Subscription confirmed',
  'Update Profile' => 'Update Profile',
  'Unsubscribe form' => 'Unsubscribe form',
  'Unsubscribe confirmation' => 'Unsubscribe confirmation',
  'Subscribe confirm email' => 'Subscribe confirm email',
  'Unsubscribe confirm email' => 'Unsubscribe confirm email',
  'Welcome email' => 'Welcome email',
  'Subscription confirmed approval' => 'Subscription confirmed approval',
  'Subscription confirmed approval email' => 'Subscription confirmed approval email',
);
