<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "list_forms" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Forms' => 'Formulare',
  'List embed forms' => 'Listen-Einbettungsformulare',
  'Your mail list forms' => 'Ihre Mailinglistenformulare',
  'Embed list forms' => 'Formulare einbetten',
  'Subscribe form' => 'Anmeldeformular',
  'Unsubscribe form' => 'Abmeldeformular',
  'Iframe version' => 'Iframe-Version',
  'Please type your email address' => 'Bitte geben Sie Ihre E-Mail-Adresse ein',
  'Unsubscribe' => 'Abmelden',
  'Please note, you will have to style the forms below to match the place where you embed them.<br /> You can create better forms by using the <a href="{sdkHref}" target="_blank">PHP-SDK</a> and connect to the provided api.' => 'Bitte beachten Sie, dass Sie die untenstehenden Formulare an den Ort anpassen müssen, an dem Sie sie einbetten.<br /> Sie können bessere Formulare erstellen, indem Sie das <a href="{sdkHref}" target="_blank">PHP-SDK</a> verwenden und sich mit der bereitgestellten API verbinden.',
);
