<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "list_pages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Pages' => 'Seiten',
  'List' => 'Liste',
  'Type' => 'Typ',
  'Content' => 'Inhalt',
  'Email subject' => 'E-Mail-Betreff',
  'The following tag is required but was not found in your content: {tag}' => 'Das folgende Tag ist erforderlich, wurde jedoch nicht in Ihrem Inhalt gefunden: {tag}',
  'List pages' => 'Listenseiten',
  'Select another list page to edit' => 'Wählen Sie eine andere Listenseite zum Bearbeiten aus',
  'Your unsubscribe form url is:' => 'Ihre Abmeldeformular-URL lautet:',
  'Preview it now!' => 'Jetzt Vorschau anzeigen!',
  'Your subscribe form url is:' => 'Ihre Anmeldeformular-URL lautet:',
  'Subscribe form' => 'Anmeldeformular',
  'Pending subscribe' => 'Anmeldung ausstehend',
  'Subscription confirmed' => 'Anmeldung bestätigt',
  'Update Profile' => 'Profil aktualisieren',
  'Unsubscribe form' => 'Abmeldeformular',
  'Unsubscribe confirmation' => 'Abmeldebestätigung',
  'Subscribe confirm email' => 'Anmeldebestätigungs-E-Mail',
  'Unsubscribe confirm email' => 'Abmeldebestätigungs-E-Mail',
  'Welcome email' => 'Willkommens-E-Mail',
  'Subscription confirmed approval' => 'Bestätigung der Anmeldung genehmigt',
  'Subscription confirmed approval email' => 'E-Mail zur Genehmigung der Anmeldebestätigung',
);
