<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "mailer" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'A very fast mailer.' => 'A very fast mailer.',
  'System testing mailer, only simulate sending.' => 'System testing mailer, only simulate sending.',
  'A fully compliant mailer.' => 'A fully compliant mailer.',
  'Next generation mailer.' => 'Next generation mailer.',
);
