<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "menus" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View menus' => 'Menüs anzeigen',
  'Menus' => 'Menüs',
  'Menu' => 'Menü',
  'Zone' => 'Zone',
  'Name' => 'Name',
  'Create new menu' => 'Neues Menü erstellen',
  'My menu name' => 'Mein Menüname',
  'Items' => 'Elemente',
  'Item' => 'Element',
  'Label' => 'Bezeichnung',
  'Title' => 'Titel',
  'Url' => 'URL',
  'Sort order' => 'Sortierreihenfolge',
  'My menu item label' => 'Bezeichnung meines Menüelements',
  'My menu item title' => 'Titel meines Menüelements',
  'My menu item url' => 'URL meines Menüelements',
  'Update menu' => 'Menü aktualisieren',
);
