<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "menus" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View menus' => 'View menus',
  'Menus' => 'Menus',
  'Menu' => 'Menu',
  'Zone' => 'Zone',
  'Name' => 'Name',
  'Create new menu' => 'Create new menu',
  'My menu name' => 'My menu name',
  'Items' => 'Items',
  'Item' => 'Item',
  'Label' => 'Label',
  'Title' => 'Title',
  'Url' => 'Url',
  'Sort order' => 'Sort order',
  'My menu item label' => 'My menu item label',
  'My menu item title' => 'My menu item title',
  'My menu item url' => 'My menu item url',
  'Update menu' => 'Update menu',
);
