<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "messages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View messages' => 'Nachrichten anzeigen',
  'Messages' => 'Nachrichten',
  'Create new message' => 'Neue Nachricht erstellen',
  'Update message' => 'Nachricht aktualisieren',
  'View message' => 'Nachricht anzeigen',
  'All messages were marked as seen!' => 'Alle Nachrichten wurden als gelesen markiert!',
  'You have {n} unread messages!' => 'Sie haben {n} ungelesene Nachrichten!',
  'See all messages' => 'Alle Nachrichten anzeigen',
  'Message' => 'Nachricht',
  'User' => 'Benutzer',
  'Title' => 'Titel',
  'Unseen' => 'Ungelesen',
  'Seen' => 'Gelesen',
  'Customer' => 'Kunde',
  'here' => 'hier',
  'Email "{email}" has requested to be blocked! You can see more details {here}!' => 'Die E-Mail-Adresse "{email}" hat beantragt, blockiert zu werden! Weitere Details finden Sie {hier}!',
  'A new abuse report has been created for the campaign "{campaign_name}". Please visit the "<a href="{abuse_reports_url}">Abuse Reports</a>" area to handle it!' => 'Ein neuer Missbrauchsbericht wurde für die Kampagne "{campaign_name}" erstellt. Bitte besuchen Sie den Bereich "<a href="{abuse_reports_url}">Missbrauchsberichte</a>", um ihn zu bearbeiten!',
  'Sync list custom fields' => 'Benutzerdefinierte Listenfelder synchronisieren',
  'Completed the sync custom fields process for the "{list}" list' => 'Der Synchronisationsprozess für benutzerdefinierte Felder der Liste "{list}" wurde abgeschlossen',
  'Started the sync custom fields process for the "{list}" list' => 'Der Synchronisationsprozess für benutzerdefinierte Felder der Liste "{list}" wurde gestartet',
  'A subscriber has been rejected from joining the {list} list because the system was not able to find a suitable delivery server to send the email' => 'Ein Abonnent wurde daran gehindert, der Liste {list} beizutreten, da das System keinen geeigneten Zustellserver für den Versand der E-Mail finden konnte',
  'Nice message to customer' => 'Nette Nachricht an den Kunden',
  'Very long and important message that should be read immediately.' => 'Sehr lange und wichtige Nachricht, die sofort gelesen werden sollte.',
);
