<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "messages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View messages' => 'View messages',
  'Messages' => 'Messages',
  'Create new message' => 'Create new message',
  'Update message' => 'Update message',
  'View message' => 'View message',
  'All messages were marked as seen!' => 'All messages were marked as seen!',
  'You have {n} unread messages!' => 'You have {n} unread messages!',
  'See all messages' => 'See all messages',
  'Message' => 'Message',
  'User' => 'User',
  'Title' => 'Title',
  'Unseen' => 'Unseen',
  'Seen' => 'Seen',
  'Customer' => 'Customer',
  'here' => 'here',
  'Email "{email}" has requested to be blocked! You can see more details {here}!' => 'Email "{email}" has requested to be blocked! You can see more details {here}!',
  'A new abuse report has been created for the campaign "{campaign_name}". Please visit the "<a href="{abuse_reports_url}">Abuse Reports</a>" area to handle it!' => 'A new abuse report has been created for the campaign "{campaign_name}". Please visit the "<a href="{abuse_reports_url}">Abuse Reports</a>" area to handle it!',
  'Sync list custom fields' => 'Sync list custom fields',
  'Completed the sync custom fields process for the "{list}" list' => 'Completed the sync custom fields process for the "{list}" list',
  'Started the sync custom fields process for the "{list}" list' => 'Started the sync custom fields process for the "{list}" list',
  'A subscriber has been rejected from joining the {list} list because the system was not able to find a suitable delivery server to send the email' => 'A subscriber has been rejected from joining the {list} list because the system was not able to find a suitable delivery server to send the email',
  'Nice message to customer' => 'Nice message to customer',
  'Very long and important message that should be read immediately.' => 'Very long and important message that should be read immediately.',
);
