<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "misc" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View campaigns delivery logs' => 'Kampagnen-Übermittlungsprotokolle anzeigen',
  'Campaigns delivery logs' => 'Kampagnen-Übermittlungsprotokolle',
  'View campaigns bounce logs' => 'Kampagnen-Bounce-Protokolle anzeigen',
  'Campaigns bounce logs' => 'Kampagnen-Bounce-Protokolle',
  'View campaigns stats' => 'Kampagnenstatistiken anzeigen',
  'View delivery servers usage logs' => 'Nutzungsprotokolle der Zustellserver anzeigen',
  'Delivery servers usage logs' => 'Nutzungsprotokolle der Zustellserver',
  'Delivery temporary errors were successfully deleted!' => 'Vorübergehende Zustellfehler wurden erfolgreich gelöscht!',
  'View PHP info' => 'PHP-Informationen anzeigen',
  'PHP info' => 'PHP-Informationen',
  'View archived logs' => 'Archivierte Protokolle anzeigen',
  'View current logs' => 'Aktuelle Protokolle anzeigen',
  'Delete delivery temporary errors' => 'Vorübergehende Zustellfehler löschen',
  'Are you sure you want to delete the delivery temporary errors? Please note that this will affect running campaigns, continue only if you really know what you are doing!' => 'Sind Sie sicher, dass Sie die vorübergehenden Zustellfehler löschen möchten? Bitte beachten Sie, dass dies laufende Kampagnen beeinflussen wird. Fahren Sie nur fort, wenn Sie wirklich wissen, was Sie tun!',
);
