<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "misc" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View campaigns delivery logs' => 'View campaigns delivery logs',
  'Campaigns delivery logs' => 'Campaigns delivery logs',
  'View campaigns bounce logs' => 'View campaigns bounce logs',
  'Campaigns bounce logs' => 'Campaigns bounce logs',
  'View campaigns stats' => 'View campaigns stats',
  'View delivery servers usage logs' => 'View delivery servers usage logs',
  'Delivery servers usage logs' => 'Delivery servers usage logs',
  'Delivery temporary errors were successfully deleted!' => 'Delivery temporary errors were successfully deleted!',
  'View PHP info' => 'View PHP info',
  'PHP info' => 'PHP info',
  'View archived logs' => 'View archived logs',
  'View current logs' => 'View current logs',
  'Delete delivery temporary errors' => 'Delete delivery temporary errors',
  'Are you sure you want to delete the delivery temporary errors? Please note that this will affect running campaigns, continue only if you really know what you are doing!' => 'Are you sure you want to delete the delivery temporary errors? Please note that this will affect running campaigns, continue only if you really know what you are doing!',
);
