<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "notes" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View notes for {name}' => 'View notes for {name}',
  'Notes' => 'Notes',
  'Note' => 'Note',
  'Created by' => 'Created by',
  'Customer' => 'Customer',
  'Title' => 'Title',
  'View notes' => 'View notes',
  'Create new note' => 'Create new note',
  'Your note contents. Please keep in mind that it will be encrypted' => 'Your note contents. Please keep in mind that it will be encrypted',
  'Update note' => 'Update note',
  'Create new note for {name}' => 'Create new note for {name}',
  'Update note for {name}' => 'Update note for {name}',
);
