<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "notes" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View notes for {name}' => 'Notizen für {name} anzeigen',
  'Notes' => 'Notizen',
  'Note' => 'Notiz',
  'Created by' => 'Erstellt von',
  'Customer' => 'Kunde',
  'Title' => 'Titel',
  'View notes' => 'Notizen anzeigen',
  'Create new note' => 'Neue Notiz erstellen',
  'Your note contents. Please keep in mind that it will be encrypted' => 'Der Inhalt Ihrer Notiz. Bitte beachten Sie, dass er verschlüsselt wird',
  'Update note' => 'Notiz aktualisieren',
  'Create new note for {name}' => 'Neue Notiz für {name} erstellen',
  'Update note for {name}' => 'Notiz für {name} aktualisieren',
);
