<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "orders" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View orders' => 'View orders',
  'Orders' => 'Orders',
  'Create order' => 'Create order',
  'Update order' => 'Update order',
  'View your order' => 'View your order',
  'Invoice' => 'Invoice',
  'Subtotal' => 'Subtotal',
  'Tax' => 'Tax',
  'Discount' => 'Discount',
  'Total' => 'Total',
  'Total due' => 'Total due',
  'Paid' => 'Paid',
  'Extra notes' => 'Extra notes',
  'Please try again later!' => 'Please try again later!',
  'Unable to create the invoices storage directory!' => 'Unable to create the invoices storage directory!',
  'Unable to create the invoice!' => 'Unable to create the invoice!',
  'Your requested invoice - {ref}' => 'Your requested invoice - {ref}',
  'The invoice has been successfully emailed!' => 'The invoice has been successfully emailed!',
  'Unable to email the invoice!' => 'Unable to email the invoice!',
  'This order applies for the "{planName}" pricing plan.' => 'This order applies for the "{planName}" pricing plan.',
  'Notes' => 'Notes',
  'Transaction info' => 'Transaction info',
  'Amount' => 'Amount',
  'Status' => 'Status',
  'Email invoice' => 'Email invoice',
  'View invoice' => 'View invoice',
  'Update this order' => 'Update this order',
  'Back to orders' => 'Back to orders',
  'View order' => 'View order',
  'Please note that any order added/changed from this area is not verified nor it goes through a payment gateway.' => 'Please note that any order added/changed from this area is not verified nor it goes through a payment gateway.',
  'Updating orders from this area is useful for offline orders mostly or for payment corrections.' => 'Updating orders from this area is useful for offline orders mostly or for payment corrections.',
  'If the order is incomplete, pending or due and changed to complete, the customer will be affected and the price plan will be assigned properly.' => 'If the order is incomplete, pending or due and changed to complete, the customer will be affected and the price plan will be assigned properly.',
  'Reference' => 'Reference',
  'Billing date' => 'Billing date',
  'Due date' => 'Due date',
  'Plan' => 'Plan',
  'Quantity' => 'Quantity',
  'Price' => 'Price',
  'Page' => 'Page',
  'of' => 'of',
  'Order' => 'Order',
  'Order no.' => 'Order no.',
  'Customer' => 'Customer',
  'Promo code' => 'Promo code',
  'Currency' => 'Currency',
  'Tax percent' => 'Tax percent',
  'Tax value' => 'Tax value',
  'The customer this order applies to, autocomplete enabled' => 'The customer this order applies to, autocomplete enabled',
  'The price plan included in this order, autocomplete enabled' => 'The price plan included in this order, autocomplete enabled',
  'The promo code applied to this order, autocomplete enabled' => 'The promo code applied to this order, autocomplete enabled',
  'Customer, autocomplete enabled' => 'Customer, autocomplete enabled',
  'Plan, autocomplete enabled' => 'Plan, autocomplete enabled',
  'Promo code, autocomplete enabled' => 'Promo code, autocomplete enabled',
  'VAT Number: {vat_number}' => 'VAT Number: {vat_number}',
  'Transaction' => 'Transaction',
  'Transaction uid' => 'Transaction uid',
  'Payment gateway name' => 'Payment gateway name',
  'Payment gateway transaction' => 'Payment gateway transaction',
  'Payment gateway response' => 'Payment gateway response',
  'Note' => 'Note',
  'If you have particular notes about this order, please type them here...' => 'If you have particular notes about this order, please type them here...',
  'Admin' => 'Admin',
  'By {author} at ' => 'By {author} at ',
  'View your orders' => 'View your orders',
  'A new order has been placed!' => 'A new order has been placed!',
  'Your order details!' => 'Your order details!',
  'Payment method' => 'Payment method',
  'Enter your promo code here' => 'Enter your promo code here',
  'Amount due' => 'Amount due',
  'Payment from' => 'Payment from',
  'Payment to' => 'Payment to',
  'Unit price' => 'Unit price',
);
