<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "pages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View pages' => 'Seiten anzeigen',
  'Pages' => 'Seiten',
  'Create new page' => 'Neue Seite erstellen',
  'Update page' => 'Seite aktualisieren',
  'Page' => 'Seite',
  'Title' => 'Titel',
  'Slug' => 'Slug',
  'Content' => 'Inhalt',
  'My page title' => 'Mein Seitentitel',
  'my-page-title' => 'mein-seitentitel',
  'This page is inactive, only site admins can see it!' => 'Diese Seite ist inaktiv, nur Seitenadministratoren können sie sehen!',
  'Active' => 'Aktiv',
);
