<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "pages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View pages' => 'View pages',
  'Pages' => 'Pages',
  'Create new page' => 'Create new page',
  'Update page' => 'Update page',
  'Page' => 'Page',
  'Title' => 'Title',
  'Slug' => 'Slug',
  'Content' => 'Content',
  'My page title' => 'My page title',
  'my-page-title' => 'my-page-title',
  'This page is inactive, only site admins can see it!' => 'This page is inactive, only site admins can see it!',
  'Active' => 'Active',
);
