<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_stripe" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Stripe payment gateway' => 'Stripe payment gateway',
  'Test secret key' => 'Test secret key',
  'Test publishable key' => 'Test publishable key',
  'Live secret key' => 'Live secret key',
  'Live publishable key' => 'Live publishable key',
  'Mode' => 'Mode',
  'Whether the payments are live or run in test mode' => 'Whether the payments are live or run in test mode',
  'Whether this gateway is enabled and can be used for payments processing' => 'Whether this gateway is enabled and can be used for payments processing',
  'The sort order for this gateway' => 'The sort order for this gateway',
  'Stripe' => 'Stripe',
  'Retrieve payments using stripe' => 'Retrieve payments using stripe',
  'Credit card number' => 'Credit card number',
  'Exp. month' => 'Exp. month',
  'Exp. year' => 'Exp. year',
  'Cvv' => 'Cvv',
  'Your credit card number seems invalid!' => 'Your credit card number seems invalid!',
  'Invalid date!' => 'Invalid date!',
  'Invalid CVV!' => 'Invalid CVV!',
  'All your data is sent over a secure connection without touching our server.' => 'All your data is sent over a secure connection without touching our server.',
  'test' => 'test',
  'live' => 'live',
);
