<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_razorpay" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Razorpay' => 'Razorpay',
  'Retrieve payments using razorpay.com' => 'Retrieve payments using razorpay.com',
  'Razorpay payment gateway' => 'Razorpay payment gateway',
  'Razorpay payments' => 'Razorpay payments',
  'Api key' => 'Api key',
  'Api secret' => 'Api secret',
  'One of your api keys as defined in your razorpay dashboard' => 'One of your api keys as defined in your razorpay dashboard',
  'The api secret for the selected api key' => 'The api secret for the selected api key',
  'Whether this gateway is enabled and can be used for payments processing' => 'Whether this gateway is enabled and can be used for payments processing',
  'The sort order for this gateway' => 'The sort order for this gateway',
  'Razorpay - www.razorpay.com' => 'Razorpay - www.razorpay.com',
);
