<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_twocheckout" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  '2Checkout' => '2Checkout',
  'Retrieve payments using 2Checkout' => 'Zahlungen mit 2Checkout abrufen',
  '2Checkout payment gateway' => '2Checkout-Zahlungsgateway',
  'Publishable key' => 'Veröffentlichbarer Schlüssel',
  'Private key' => 'Privater Schlüssel',
  'Seller ID / Account number' => 'Verkäufer-ID / Kontonummer',
  'Mode' => 'Modus',
  'Whether the payments are live or run in sandbox mode' => 'Ob die Zahlungen live oder im Sandbox-Modus ausgeführt werden',
  'Whether this gateway is enabled and can be used for payments processing' => 'Ob dieses Gateway aktiviert ist und für die Zahlungsabwicklung verwendet werden kann',
  'The sort order for this gateway' => 'Die Sortierreihenfolge für dieses Gateway',
  'Credit card number' => 'Kreditkartennummer',
  'Exp. month' => 'Ablaufmonat',
  'Exp. year' => 'Ablaufjahr',
  'Cvv' => 'Cvv',
  'Please wait, processing your request, this might take a while...' => 'Bitte warten Sie, Ihre Anfrage wird bearbeitet, dies kann eine Weile dauern...',
  'All your data is sent over a secure connection without touching our server.' => 'Alle Ihre Daten werden über eine sichere Verbindung gesendet, ohne unseren Server zu berühren.',
  'Please go to your {account} and fill in your company info before checking out.' => 'Bitte gehen Sie zu Ihrem {account} und füllen Sie Ihre Unternehmensinformationen aus, bevor Sie zur Kasse gehen.',
  'account' => 'Konto',
);
