<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_payza" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Payza' => 'Payza',
  'Retrieve payments using payza.eu' => 'Retrieve payments using payza.eu',
  'Payza payment gateway' => 'Payza payment gateway',
  'Email' => 'Email',
  'Mode' => 'Mode',
  'Your payza email address where the payments should go' => 'Your payza email address where the payments should go',
  'Whether the payments are live or run in sandbox' => 'Whether the payments are live or run in sandbox',
  'Whether this gateway is enabled and can be used for payments processing' => 'Whether this gateway is enabled and can be used for payments processing',
  'The sort order for this gateway' => 'The sort order for this gateway',
  'You will be redirected to pay securely on payza.eu official website!' => 'You will be redirected to pay securely on payza.eu official website!',
  'Your order is in "{status}" status, it usually takes a few minutes to be processed and if everything is fine, your pricing plan will become active!' => 'Your order is in "{status}" status, it usually takes a few minutes to be processed and if everything is fine, your pricing plan will become active!',
);
