<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_authorize_net" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'AuthorizeNet payment gateway' => 'AuthorizeNet payment gateway',
  'Api login ID' => 'Api login ID',
  'Transaction key' => 'Transaction key',
  'Mode' => 'Mode',
  'Whether the payments are live or run in sandbox mode' => 'Whether the payments are live or run in sandbox mode',
  'Whether this gateway is enabled and can be used for payments processing' => 'Whether this gateway is enabled and can be used for payments processing',
  'The sort order for this gateway' => 'The sort order for this gateway',
  'AuthorizeNet' => 'AuthorizeNet',
  'Retrieve payments using authorize net' => 'Retrieve payments using authorize net',
  'Credit card number' => 'Credit card number',
  'Exp. month' => 'Exp. month',
  'Exp. year' => 'Exp. year',
);
