<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_stripe_subscriptions" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Stripe subscriptions' => 'Stripe subscriptions',
  'Retrieve payments using stripe subscriptions' => 'Retrieve payments using stripe subscriptions',
  'Stripe subscriptions payment gateway' => 'Stripe subscriptions payment gateway',
  'Please do not forget to add the webhook url into your Stripe dashboard, this is maybe the most important thing you have to do, without it, customers will not be assigned to customer groups.' => 'Please do not forget to add the webhook url into your Stripe dashboard, this is maybe the most important thing you have to do, without it, customers will not be assigned to customer groups.',
  'The webhook url that you have to add is: {url}' => 'The webhook url that you have to add is: {url}',
  'Please note that {here} you have a screenshot showing how the webhook has to be added and what event type you must select.' => 'Please note that {here} you have a screenshot showing how the webhook has to be added and what event type you must select.',
  'Subscriptions are created on a monthly basis, so please make sure your customer groups sending quota targets the monthly time unit, this is very important.' => 'Subscriptions are created on a monthly basis, so please make sure your customer groups sending quota targets the monthly time unit, this is very important.',
  'test' => 'test',
  'live' => 'live',
  'Test secret key' => 'Test secret key',
  'Test publishable key' => 'Test publishable key',
  'Live secret key' => 'Live secret key',
  'Live publishable key' => 'Live publishable key',
  'Expiration move to group' => 'Expiration move to group',
  'Mode' => 'Mode',
  'Whether to move the customer in this group when the subscription ends' => 'Whether to move the customer in this group when the subscription ends',
  'Whether the payments are live or run in test mode' => 'Whether the payments are live or run in test mode',
  'Whether this gateway is enabled and can be used for payments processing' => 'Whether this gateway is enabled and can be used for payments processing',
  'The sort order for this gateway' => 'The sort order for this gateway',
  'Subscriptions' => 'Subscriptions',
);
