<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_paypal" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Your order is in "{status}" status, it usually takes a few minutes to be processed and if everything is fine, your pricing plan will become active!' => 'Your order is in "{status}" status, it usually takes a few minutes to be processed and if everything is fine, your pricing plan will become active!',
  'Paypal' => 'Paypal',
  'Retrieve payments using paypal' => 'Retrieve payments using paypal',
  'Paypal payment gateway' => 'Paypal payment gateway',
  'Email' => 'Email',
  'Mode' => 'Mode',
  'Your paypal email address where the payments should go' => 'Your paypal email address where the payments should go',
  'Whether the payments are live or run in sandbox' => 'Whether the payments are live or run in sandbox',
  'Whether this gateway is enabled and can be used for payments processing' => 'Whether this gateway is enabled and can be used for payments processing',
  'The sort order for this gateway' => 'The sort order for this gateway',
  'You will be redirected to pay securely on paypal.com official website!' => 'You will be redirected to pay securely on paypal.com official website!',
  'sandbox' => 'sandbox',
  'live' => 'live',
);
