<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_stripe_subscriptions" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Stripe subscriptions' => 'Stripe-Abonnements',
  'Retrieve payments using stripe subscriptions' => 'Zahlungen mit Stripe-Abonnements abrufen',
  'Stripe subscriptions payment gateway' => 'Stripe-Abonnement-Zahlungsgateway',
  'Please do not forget to add the webhook url into your Stripe dashboard, this is maybe the most important thing you have to do, without it, customers will not be assigned to customer groups.' => 'Bitte vergessen Sie nicht, die Webhook-URL in Ihrem Stripe-Dashboard hinzuzufügen. Dies ist möglicherweise das Wichtigste, was Sie tun müssen. Ohne sie werden Kunden nicht Kundengruppen zugewiesen.',
  'The webhook url that you have to add is: {url}' => 'Die Webhook-URL, die Sie hinzufügen müssen, lautet: {url}',
  'Please note that {here} you have a screenshot showing how the webhook has to be added and what event type you must select.' => 'Bitte beachten Sie, dass Sie {here} einen Screenshot haben, der zeigt, wie der Webhook hinzugefügt werden muss und welchen Ereignistyp Sie auswählen müssen.',
  'Subscriptions are created on a monthly basis, so please make sure your customer groups sending quota targets the monthly time unit, this is very important.' => 'Abonnements werden monatlich erstellt. Bitte stellen Sie sicher, dass die Versandquote Ihrer Kundengruppen auf die monatliche Zeiteinheit ausgerichtet ist. Dies ist sehr wichtig.',
  'test' => 'Test',
  'live' => 'Live',
  'Test secret key' => 'Geheimer Testschlüssel',
  'Test publishable key' => 'Veröffentlichbarer Testschlüssel',
  'Live secret key' => 'Geheimer Live-Schlüssel',
  'Live publishable key' => 'Veröffentlichbarer Live-Schlüssel',
  'Expiration move to group' => 'Ablauf verschieben in Gruppe',
  'Mode' => 'Modus',
  'Whether to move the customer in this group when the subscription ends' => 'Ob der Kunde in diese Gruppe verschoben wird, wenn das Abonnement endet',
  'Whether the payments are live or run in test mode' => 'Ob die Zahlungen live oder im Testmodus ausgeführt werden',
  'Whether this gateway is enabled and can be used for payments processing' => 'Ob dieses Gateway aktiviert ist und für die Zahlungsabwicklung verwendet werden kann',
  'The sort order for this gateway' => 'Die Sortierreihenfolge für dieses Gateway',
  'Subscriptions' => 'Abonnements',
);
