<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_offline" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Offline payment' => 'Offline payment',
  'Your order is in "{status}" status, once it gets approved, your pricing plan will become active!' => 'Your order is in "{status}" status, once it gets approved, your pricing plan will become active!',
  'Offline' => 'Offline',
  'Retrieve payments offline' => 'Retrieve payments offline',
  'Offline payment gateway' => 'Offline payment gateway',
  'Offline payments' => 'Offline payments',
  'Description' => 'Description',
  'The needed details for customers to see and to use in order to make the offline payment' => 'The needed details for customers to see and to use in order to make the offline payment',
  'Whether this gateway is enabled and can be used for payments processing' => 'Whether this gateway is enabled and can be used for payments processing',
  'The sort order for this gateway' => 'The sort order for this gateway',
);
