<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_stripe" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Stripe payment gateway' => 'Stripe-Zahlungsgateway',
  'Test secret key' => 'Geheimer Testschlüssel',
  'Test publishable key' => 'Veröffentlichbarer Testschlüssel',
  'Live secret key' => 'Geheimer Live-Schlüssel',
  'Live publishable key' => 'Veröffentlichbarer Live-Schlüssel',
  'Mode' => 'Modus',
  'Whether the payments are live or run in test mode' => 'Ob die Zahlungen live oder im Testmodus ausgeführt werden',
  'Whether this gateway is enabled and can be used for payments processing' => 'Ob dieses Gateway aktiviert ist und für die Zahlungsabwicklung verwendet werden kann',
  'The sort order for this gateway' => 'Die Sortierreihenfolge für dieses Gateway',
  'Stripe' => 'Stripe',
  'Retrieve payments using stripe' => 'Zahlungen mit Stripe abrufen',
  'Credit card number' => 'Kreditkartennummer',
  'Exp. month' => 'Ablaufmonat',
  'Exp. year' => 'Ablaufjahr',
  'Cvv' => 'Cvv',
  'Your credit card number seems invalid!' => 'Ihre Kreditkartennummer scheint ungültig zu sein!',
  'Invalid date!' => 'Ungültiges Datum!',
  'Invalid CVV!' => 'Ungültiger CVV!',
  'All your data is sent over a secure connection without touching our server.' => 'Alle Ihre Daten werden über eine sichere Verbindung gesendet, ohne unseren Server zu berühren.',
  'test' => 'Test',
  'live' => 'Live',
);
