<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_mollie" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Mollie' => 'Mollie',
  'Retrieve payments using mollie' => 'Retrieve payments using mollie',
  'Mollie payment gateway' => 'Mollie payment gateway',
  'Credit card number' => 'Credit card number',
  'Exp. month' => 'Exp. month',
  'Exp. year' => 'Exp. year',
  'Cvv' => 'Cvv',
);
