<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_twocheckout" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  '2Checkout' => '2Checkout',
  'Retrieve payments using 2Checkout' => 'Retrieve payments using 2Checkout',
  '2Checkout payment gateway' => '2Checkout payment gateway',
  'Publishable key' => 'Publishable key',
  'Private key' => 'Private key',
  'Seller ID / Account number' => 'Seller ID / Account number',
  'Mode' => 'Mode',
  'Whether the payments are live or run in sandbox mode' => 'Whether the payments are live or run in sandbox mode',
  'Whether this gateway is enabled and can be used for payments processing' => 'Whether this gateway is enabled and can be used for payments processing',
  'The sort order for this gateway' => 'The sort order for this gateway',
  'Credit card number' => 'Credit card number',
  'Exp. month' => 'Exp. month',
  'Exp. year' => 'Exp. year',
  'Cvv' => 'Cvv',
  'Please wait, processing your request, this might take a while...' => 'Please wait, processing your request, this might take a while...',
  'All your data is sent over a secure connection without touching our server.' => 'All your data is sent over a secure connection without touching our server.',
  'Please go to your {account} and fill in your company info before checking out.' => 'Please go to your {account} and fill in your company info before checking out.',
  'account' => 'account',
);
