<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "price_plans" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View price plans' => 'View price plans',
  'Price plans' => 'Price plans',
  'Create new price plan' => 'Create new price plan',
  'Update price plan' => 'Update price plan',
  'Your price plan has been successfully copied!' => 'Your price plan has been successfully copied!',
  'Unable to copy the price plan!' => 'Unable to copy the price plan!',
  'Plan' => 'Plan',
  'Plan uid' => 'Plan uid',
  'Customer group' => 'Customer group',
  'Name' => 'Name',
  'Price' => 'Price',
  'Description' => 'Description',
  'Recommended' => 'Recommended',
  'Visible' => 'Visible',
  'The group where the customer will be moved after purchasing this plan. Make sure the group has proper permissions and limits' => 'The group where the customer will be moved after purchasing this plan. Make sure the group has proper permissions and limits',
  'The price plan name, used in customer display area, orders, etc' => 'The price plan name, used in customer display area, orders, etc',
  'The amount the customers will be charged when buying this plan' => 'The amount the customers will be charged when buying this plan',
  'A detailed description about the price plan features' => 'A detailed description about the price plan features',
  'Whether this plan has the recommended badge on it' => 'Whether this plan has the recommended badge on it',
  'Whether this plan is visible in customers area' => 'Whether this plan is visible in customers area',
  'Price plan' => 'Price plan',
  'Submit payment' => 'Submit payment',
  'Place offline order' => 'Place offline order',
  'Unable to load the payment gateway!' => 'Unable to load the payment gateway!',
  'Invalid payment gateway setup!' => 'Invalid payment gateway setup!',
  'The specified price plan is invalid!' => 'The specified price plan is invalid!',
  'Selected price plan allows {n} {w} but you already have {m}, therefore you cannot apply for the plan!' => 'Selected price plan allows {n} {w} but you already have {m}, therefore you cannot apply for the plan!',
  'Unable to set a correct currency!' => 'Unable to set a correct currency!',
  'Price plans payment' => 'Price plans payment',
  'Unable to load payment data!' => 'Unable to load payment data!',
  'Invalid currency specified!' => 'Invalid currency specified!',
  'Cannot save your order!' => 'Cannot save your order!',
  'The provided promotional code does not exists anymore!' => 'The provided promotional code does not exists anymore!',
  'This promo code requires that select a price plan that costs at least {amount}!' => 'This promo code requires that select a price plan that costs at least {amount}!',
  'You have reached the maximum usage times for this promo code!' => 'You have reached the maximum usage times for this promo code!',
  'This promo code has reached the maximum usage times!' => 'This promo code has reached the maximum usage times!',
  'The promo code has been successfully applied!' => 'The promo code has been successfully applied!',
  'You have selected the "{planName}" pricing plan.' => 'You have selected the "{planName}" pricing plan.',
  'Apply code' => 'Apply code',
  'Available price plans' => 'Available price plans',
  'Select payment method' => 'Select payment method',
  'Payment gateway selection' => 'Payment gateway selection',
  'Proceed to payment' => 'Proceed to payment',
  'Congratulations, you have successfully purchased the price plan!' => 'Congratulations, you have successfully purchased the price plan!',
  'The payment id is missing.' => 'The payment id is missing.',
  'Something went wrong!' => 'Something went wrong!',
  'The payment could not be retrieved.' => 'The payment could not be retrieved.',
  'Subscription created in Mollie. Waiting for the webhook with the payment to activate it' => 'Subscription created in Mollie. Waiting for the webhook with the payment to activate it',
  'The Mollie subscription is not active. Since the payment is made you should check your Mollie account.' => 'The Mollie subscription is not active. Since the payment is made you should check your Mollie account.',
  'The order id could not be retrieved from the Mollie payment meta.' => 'The order id could not be retrieved from the Mollie payment meta.',
  'The customer id could not be retrieved from the Mollie payment meta.' => 'The customer id could not be retrieved from the Mollie payment meta.',
  'Please note that plan activation can take a few minutes!' => 'Please note that plan activation can take a few minutes!',
  'Your payment has been declined!' => 'Your payment has been declined!',
  'Place order' => 'Place order',
  'The order could not be retrieved.' => 'The order could not be retrieved.',
  'The customer could not be retrieved.' => 'The customer could not be retrieved.',
);
