<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "promo_codes" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View promo codes' => 'Promo-Codes anzeigen',
  'Promo codes' => 'Promo-Codes',
  'Create new promo code' => 'Neuen Promo-Code erstellen',
  'Update promo code' => 'Promo-Code aktualisieren',
  'Code' => 'Code',
  'Type' => 'Typ',
  'Discount' => 'Rabatt',
  'Total amount' => 'Gesamtbetrag',
  'Total usage' => 'Gesamtnutzung',
  'Customer usage' => 'Kundennutzung',
  'Date start' => 'Startdatum',
  'Date end' => 'Enddatum',
  'The promotional code' => 'Der Promo-Code',
  'The type of the promotional code' => 'Der Typ des Promo-Codes',
  'The discount received after applying this promotional code' => 'Der Rabatt, der nach Anwendung dieses Promo-Codes gewährt wird',
  'The amount of the price plan in order for this promotional code to apply' => 'Der Betrag des Preisplans, damit dieser Promo-Code gilt',
  'The maximum number of usages for this promotional code. Set it to 0 for unlimited' => 'Die maximale Anzahl der Nutzungen für diesen Promo-Code. Auf 0 setzen für unbegrenzt',
  'How many times a customer can use this promotional code. Set it to 0 for unlimited' => 'Wie oft ein Kunde diesen Promo-Code nutzen kann. Auf 0 setzen für unbegrenzt',
  'The start date for this promotional code' => 'Das Startdatum für diesen Promo-Code',
  'The end date for this promotional code' => 'Das Enddatum für diesen Promo-Code',
  'i.e: FREE100' => 'z. B.: FREE100',
  'i.e: 10' => 'z. B.: 10',
  'i.e: 30' => 'z. B.: 30',
  'i.e: 1' => 'z. B.: 1',
  'i.e: {date}' => 'z. B.: {date}',
  'fixed amount' => 'fester Betrag',
  'percentage' => 'Prozentsatz',
  'i.e: 2021-11-05' => 'z. B.: 2021-11-05',
  'i.e: 2021-12-05' => 'z. B.: 2021-12-05',
  'i.e: 2021-11-26' => 'z. B.: 2021-11-26',
  'i.e: 2021-12-26' => 'z. B.: 2021-12-26',
  'i.e: 2021-11-27' => 'z. B.: 2021-11-27',
  'i.e: 2021-12-27' => 'z. B.: 2021-12-27',
  'i.e: 2021-11-29' => 'z. B.: 2021-11-29',
  'i.e: 2021-12-29' => 'z. B.: 2021-12-29',
  'i.e: 2023-11-17' => 'z. B.: 2023-11-17',
  'i.e: 2023-12-17' => 'z. B.: 2023-12-17',
  'i.e: 2024-08-26' => 'z. B.: 2024-08-26',
  'i.e: 2024-09-25' => 'z. B.: 2024-09-25',
  'i.e: 2024-08-27' => 'z. B.: 2024-08-27',
  'i.e: 2024-09-26' => 'z. B.: 2024-09-26',
);
