<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "promo_codes" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View promo codes' => 'View promo codes',
  'Promo codes' => 'Promo codes',
  'Create new promo code' => 'Create new promo code',
  'Update promo code' => 'Update promo code',
  'Code' => 'Code',
  'Type' => 'Type',
  'Discount' => 'Discount',
  'Total amount' => 'Total amount',
  'Total usage' => 'Total usage',
  'Customer usage' => 'Customer usage',
  'Date start' => 'Date start',
  'Date end' => 'Date end',
  'The promotional code' => 'The promotional code',
  'The type of the promotional code' => 'The type of the promotional code',
  'The discount received after applying this promotional code' => 'The discount received after applying this promotional code',
  'The amount of the price plan in order for this promotional code to apply' => 'The amount of the price plan in order for this promotional code to apply',
  'The maximum number of usages for this promotional code. Set it to 0 for unlimited' => 'The maximum number of usages for this promotional code. Set it to 0 for unlimited',
  'How many times a customer can use this promotional code. Set it to 0 for unlimited' => 'How many times a customer can use this promotional code. Set it to 0 for unlimited',
  'The start date for this promotional code' => 'The start date for this promotional code',
  'The end date for this promotional code' => 'The end date for this promotional code',
  'i.e: FREE100' => 'i.e: FREE100',
  'i.e: 10' => 'i.e: 10',
  'i.e: 30' => 'i.e: 30',
  'i.e: 1' => 'i.e: 1',
  'i.e: {date}' => 'i.e: {date}',
  'fixed amount' => 'fixed amount',
  'percentage' => 'percentage',
  'i.e: 2021-11-05' => 'i.e: 2021-11-05',
  'i.e: 2021-12-05' => 'i.e: 2021-12-05',
  'i.e: 2021-11-26' => 'i.e: 2021-11-26',
  'i.e: 2021-12-26' => 'i.e: 2021-12-26',
  'i.e: 2021-11-27' => 'i.e: 2021-11-27',
  'i.e: 2021-12-27' => 'i.e: 2021-12-27',
  'i.e: 2021-11-29' => 'i.e: 2021-11-29',
  'i.e: 2021-12-29' => 'i.e: 2021-12-29',
  'i.e: 2023-11-17' => 'i.e: 2023-11-17',
  'i.e: 2023-12-17' => 'i.e: 2023-12-17',
  'i.e: 2024-08-26' => 'i.e: 2024-08-26',
  'i.e: 2024-09-25' => 'i.e: 2024-09-25',
  'i.e: 2024-08-27' => 'i.e: 2024-08-27',
  'i.e: 2024-09-26' => 'i.e: 2024-09-26',
);
