<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "queue" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View queue tasks' => 'View queue tasks',
  'ID' => 'ID',
  'Message ID' => 'Message ID',
  'Queue' => 'Queue',
  'User' => 'User',
  'Customer' => 'Customer',
  'Acknowledged' => 'Acknowledged',
  'Reject' => 'Reject',
  'Requeue' => 'Requeue',
  'Already acknowledged' => 'Already acknowledged',
  'Waiting' => 'Waiting',
  'Processing' => 'Processing',
);
