<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "recaptcha" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Recaptcha' => 'Recaptcha',
  'Common' => 'Common',
  'Additional domains and key pairs' => 'Additional domains and key pairs',
  'Domain' => 'Domain',
  'Site key' => 'Site key',
  'Secret key' => 'Secret key',
  'The domain(s) where this key pair will be applied' => 'The domain(s) where this key pair will be applied',
  'The site key for recaptcha service' => 'The site key for recaptcha service',
  'The secret key for recaptcha service' => 'The secret key for recaptcha service',
  'Invalid domains: {domains}' => 'Invalid domains: {domains}',
  'Enabled for list forms' => 'Enabled for list forms',
  'Enable for registration' => 'Enable for registration',
  'Enable for login' => 'Enable for login',
  'Enable for forgot password' => 'Enable for forgot password',
  'Whether the feature is enabled for list forms' => 'Whether the feature is enabled for list forms',
  'Whether the feature is enabled for registration' => 'Whether the feature is enabled for registration',
  'Whether the feature is enabled for login' => 'Whether the feature is enabled for login',
  'Whether the feature is enabled for forgot password' => 'Whether the feature is enabled for forgot password',
  'Enabled for public block email form' => 'Enabled for public block email form',
  'Whether the feature is enabled for public block email form' => 'Whether the feature is enabled for public block email form',
);
