<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "recaptcha" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Recaptcha' => 'ReCaptcha',
  'Common' => 'Allgemein',
  'Additional domains and key pairs' => 'Zusätzliche Domains und Schlüsselpaaren',
  'Domain' => 'Domain',
  'Site key' => 'Seitenschlüssel',
  'Secret key' => 'Geheimschlüssel',
  'The domain(s) where this key pair will be applied' => 'Die Domain(s), auf die dieses Schlüsselpaar angewendet wird',
  'The site key for recaptcha service' => 'Der Seitenschlüssel für den ReCaptcha-Dienst',
  'The secret key for recaptcha service' => 'Der Geheimschlüssel für den ReCaptcha-Dienst',
  'Invalid domains: {domains}' => 'Ungültige Domains: {domains}',
  'Enabled for list forms' => 'Aktiviert für Listenformulare',
  'Enable for registration' => 'Für Registrierung aktivieren',
  'Enable for login' => 'Für Login aktivieren',
  'Enable for forgot password' => 'Für Passwort vergessen aktivieren',
  'Whether the feature is enabled for list forms' => 'Ob die Funktion für Listenformulare aktiviert ist',
  'Whether the feature is enabled for registration' => 'Ob die Funktion für die Registrierung aktiviert ist',
  'Whether the feature is enabled for login' => 'Ob die Funktion für den Login aktiviert ist',
  'Whether the feature is enabled for forgot password' => 'Ob die Funktion für Passwort vergessen aktiviert ist',
  'Enabled for public block email form' => 'Aktiviert für öffentliches Block-E-Mail-Formular',
  'Whether the feature is enabled for public block email form' => 'Ob die Funktion für das öffentliche Block-E-Mail-Formular aktiviert ist',
);
