<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "start_pages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Start pages' => 'Startseiten',
  'Create new page' => 'Neue Seite erstellen',
  'Update page' => 'Seite aktualisieren',
  'Select icon color' => 'Symbolfarbe auswählen',
  'Reset icon color' => 'Symbolfarbe zurücksetzen',
  'Remove icon' => 'Symbol entfernen',
  'You can use following tags in heading and content:' => 'Sie können die folgenden Tags in Überschrift und Inhalt verwenden:',
  'Tag' => 'Tag',
  'Description' => 'Beschreibung',
  'Page' => 'Seite',
  'Application' => 'Anwendung',
  'Route' => 'Route',
  'Icon' => 'Symbol',
  'Heading' => 'Überschrift',
  'Content' => 'Inhalt',
  'The application where this page applies' => 'Die Anwendung, auf die sich diese Seite bezieht',
  'The url route (controller/action) where this page applies, i.e: campaigns/index' => 'Die URL-Route (Controller/Aktion), auf die sich diese Seite bezieht, z. B.: campaigns/index',
  'The heading of the page' => 'Die Überschrift der Seite',
  'Start by typing a few characters from the icon name' => 'Beginnen Sie mit der Eingabe einiger Zeichen des Symbolnamens',
  'Search icon, i.e: envelope' => 'Symbol suchen, z. B.: Umschlag',
  'The route does not seem to be valid!' => 'Die Route scheint nicht gültig zu sein!',
  'The application/route combo is already taken!' => 'Die Kombination aus Anwendung und Route ist bereits vergeben!',
  'Customer base url, useful for links generation.' => 'Kunden-Basis-URL, nützlich für die Link-Generierung.',
  'Backend base url, useful for links generation.' => 'Backend-Basis-URL, nützlich für die Link-Generierung.',
  'Frontend base url, useful for links generation.' => 'Frontend-Basis-URL, nützlich für die Link-Generierung.',
  'Given color code does not seem to be a valid hex code!' => 'Der angegebene Farbcode scheint kein gültiger Hex-Code zu sein!',
  'Api' => 'API',
  'Backend' => 'Backend',
  'Customer' => 'Kunde',
  'Frontend' => 'Frontend',
);
