<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "start_pages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Start pages' => 'Start pages',
  'Create new page' => 'Create new page',
  'Update page' => 'Update page',
  'Select icon color' => 'Select icon color',
  'Reset icon color' => 'Reset icon color',
  'Remove icon' => 'Remove icon',
  'You can use following tags in heading and content:' => 'You can use following tags in heading and content:',
  'Tag' => 'Tag',
  'Description' => 'Description',
  'Page' => 'Page',
  'Application' => 'Application',
  'Route' => 'Route',
  'Icon' => 'Icon',
  'Heading' => 'Heading',
  'Content' => 'Content',
  'The application where this page applies' => 'The application where this page applies',
  'The url route (controller/action) where this page applies, i.e: campaigns/index' => 'The url route (controller/action) where this page applies, i.e: campaigns/index',
  'The heading of the page' => 'The heading of the page',
  'Start by typing a few characters from the icon name' => 'Start by typing a few characters from the icon name',
  'Search icon, i.e: envelope' => 'Search icon, i.e: envelope',
  'The route does not seem to be valid!' => 'The route does not seem to be valid!',
  'The application/route combo is already taken!' => 'The application/route combo is already taken!',
  'Customer base url, useful for links generation.' => 'Customer base url, useful for links generation.',
  'Backend base url, useful for links generation.' => 'Backend base url, useful for links generation.',
  'Frontend base url, useful for links generation.' => 'Frontend base url, useful for links generation.',
  'Given color code does not seem to be a valid hex code!' => 'Given color code does not seem to be a valid hex code!',
  'Api' => 'Api',
  'Backend' => 'Backend',
  'Customer' => 'Customer',
  'Frontend' => 'Frontend',
);
