<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "subscribe_by_email" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Subscribe by email' => 'Per E-Mail abonnieren',
  'Common' => 'Allgemein',
  'The absolute path to the pipe file is: {path}.' => 'Der absolute Pfad zur Pipe-Datei lautet: {path}.',
  'The relative path to the pipe file is: {path}.' => 'Der relative Pfad zur Pipe-Datei lautet: {path}.',
  'here' => 'hier',
  'Before proceeding any further, please read the setup guide located {here}.' => 'Bevor Sie fortfahren, lesen Sie bitte die Einrichtungsanleitung unter {hier}.',
  'Parse the SUBJECT header from the incoming emails' => 'Den Betreff-Header aus eingehenden E-Mails analysieren',
  'Parse the TO header from the incoming emails' => 'Den An-Header aus eingehenden E-Mails analysieren',
  'Parse BOTH of the above' => 'BEIDE der oben genannten analysieren',
  'Email' => 'E-Mail',
  'Parse header' => 'Header analysieren',
  'The email address where incoming emails will be piped to' => 'Die E-Mail-Adresse, an die eingehende E-Mails weitergeleitet werden',
  'See the info about header parsing' => 'Informationen zur Header-Analyse anzeigen',
);
