<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "subscribe_by_email" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Subscribe by email' => 'Subscribe by email',
  'Common' => 'Common',
  'The absolute path to the pipe file is: {path}.' => 'The absolute path to the pipe file is: {path}.',
  'The relative path to the pipe file is: {path}.' => 'The relative path to the pipe file is: {path}.',
  'here' => 'here',
  'Before proceeding any further, please read the setup guide located {here}.' => 'Before proceeding any further, please read the setup guide located {here}.',
  'Parse the SUBJECT header from the incoming emails' => 'Parse the SUBJECT header from the incoming emails',
  'Parse the TO header from the incoming emails' => 'Parse the TO header from the incoming emails',
  'Parse BOTH of the above' => 'Parse BOTH of the above',
  'Email' => 'Email',
  'Parse header' => 'Parse header',
  'The email address where incoming emails will be piped to' => 'The email address where incoming emails will be piped to',
  'See the info about header parsing' => 'See the info about header parsing',
);
