<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "support_tickets" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Support tickets' => 'Support tickets',
  'View all' => 'View all',
  '{site} support' => '{site} support',
  '[{site} support] {subject}' => '[{site} support] {subject}',
  'This ticket has been assigned to {user} already, replying to it will assign you to the ticket.' => 'This ticket has been assigned to {user} already, replying to it will assign you to the ticket.',
  'View support ticket' => 'View support ticket',
  'Support tickets settings' => 'Support tickets settings',
  'Settings' => 'Settings',
  'Support tickets priorities' => 'Support tickets priorities',
  'Priorities' => 'Priorities',
  'Support tickets departments' => 'Support tickets departments',
  'Departments' => 'Departments',
  'Assigned users' => 'Assigned users',
  'Select one or more users assigned to respond to tickets for this department. Selected users will receive emails each time a support ticket is created and this department selected. If no user is selected, then all system users will receive emails.' => 'Select one or more users assigned to respond to tickets for this department. Selected users will receive emails each time a support ticket is created and this department selected. If no user is selected, then all system users will receive emails.',
  'Hello {nameA}, this ticket reply has been posted by {nameB} and requires your attention. Please read the ticket reply content below:' => 'Hello {nameA}, this ticket reply has been posted by {nameB} and requires your attention. Please read the ticket reply content below:',
  'Posted by {name}' => 'Posted by {name}',
  'Support team' => 'Support team',
  'At {date}' => 'At {date}',
  'Department: {department}' => 'Department: {department}',
  'Priority: {priority}' => 'Priority: {priority}',
  'You can follow the url below in order to reply to this ticket:' => 'You can follow the url below in order to reply to this ticket:',
  'Thank you!' => 'Thank you!',
  '{site} support team' => '{site} support team',
  'Hello {nameA}, this ticket has been posted by {nameB} and requires your attention. Please read the ticket content below:' => 'Hello {nameA}, this ticket has been posted by {nameB} and requires your attention. Please read the ticket content below:',
  'Ticket #{num}' => 'Ticket #{num}',
  'Subject: {subject}' => 'Subject: {subject}',
  'Assigned to' => 'Assigned to',
  'Customer' => 'Customer',
  'Department' => 'Department',
  'Priority' => 'Priority',
  'Ip address' => 'Ip address',
  'Rating' => 'Rating',
  'Status' => 'Status',
  'Date added' => 'Date added',
  'Last updated' => 'Last updated',
  'Reply to this ticket' => 'Reply to this ticket',
  'Send reply' => 'Send reply',
  'Showing all {n} replies:' => 'Showing all {n} replies:',
  'Showing {n} reply:' => 'Showing {n} reply:',
  'Reply #{num}' => 'Reply #{num}',
  'From {ip} at {date}' => 'From {ip} at {date}',
  'Delete this reply' => 'Delete this reply',
  'Reply rated {rate} out of {max}' => 'Reply rated {rate} out of {max}',
  'Rating enabled' => 'Rating enabled',
  'Rating timeframe' => 'Rating timeframe',
  'Inactive tickets close days' => 'Inactive tickets close days',
  'Provide support only for these customer groups' => 'Provide support only for these customer groups',
  'Whether rating is enabled and customer are able to rate your replies' => 'Whether rating is enabled and customer are able to rate your replies',
  'After how many hours should we deny the customer the ability to rate a staff reply' => 'After how many hours should we deny the customer the ability to rate a staff reply',
  'After how many days inactive tickets should be closed automatically' => 'After how many days inactive tickets should be closed automatically',
  'Name' => 'Name',
  'Reply' => 'Reply',
  'Ticket' => 'Ticket',
  'User' => 'User',
  'Content' => 'Content',
  'And' => 'And',
  'Subject' => 'Subject',
  'Replies' => 'Replies',
  'Customer (autocomplete enabled)' => 'Customer (autocomplete enabled)',
  'This reply cannot be rated anymore.' => 'This reply cannot be rated anymore.',
  'Thank you, your rating has been successfully applied.' => 'Thank you, your rating has been successfully applied.',
  'Rate this reply' => 'Rate this reply',
  'Submit ticket' => 'Submit ticket',
  'Open' => 'Open',
  'Waiting staff reply' => 'Waiting staff reply',
  'Waiting customer reply' => 'Waiting customer reply',
  'Closed' => 'Closed',
);
