<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "suppression_lists" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Email' => 'Email',
  'List' => 'List',
  'The email address {email} is already in your suppression list!' => 'The email address {email} is already in your suppression list!',
  'Please enter a valid email address!' => 'Please enter a valid email address!',
  'Customer' => 'Customer',
  'Name' => 'Name',
  'Emails count' => 'Emails count',
  'Suppression list emails' => 'Suppression list emails',
  'Suppression lists' => 'Suppression lists',
  'Create new' => 'Create new',
  'Update' => 'Update',
  'Cannot open export temporary file!' => 'Cannot open export temporary file!',
  'Your file does not contain the header with the fields title!' => 'Your file does not contain the header with the fields title!',
  'Your file has been successfuly imported, from {count} records, {total} were imported!' => 'Your file has been successfuly imported, from {count} records, {total} were imported!',
  'Unable to move the uploaded file!' => 'Unable to move the uploaded file!',
  'Your file has been successfully queued for processing and you will be notified when processing is done!' => 'Your file has been successfully queued for processing and you will be notified when processing is done!',
  'Import from CSV file' => 'Import from CSV file',
  'Please note, the csv file must contain a header with the email column.' => 'Please note, the csv file must contain a header with the email column.',
  'If unsure about how to format your file, do an export first and see how the file looks.' => 'If unsure about how to format your file, do an export first and see how the file looks.',
);
