<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "suppression_lists" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Email' => 'E-Mail',
  'List' => 'Liste',
  'The email address {email} is already in your suppression list!' => 'Die E-Mail-Adresse {email} befindet sich bereits in Ihrer Sperrliste!',
  'Please enter a valid email address!' => 'Bitte geben Sie eine gültige E-Mail-Adresse ein!',
  'Customer' => 'Kunde',
  'Name' => 'Name',
  'Emails count' => 'E-Mail-Anzahl',
  'Suppression list emails' => 'E-Mails in der Sperrliste',
  'Suppression lists' => 'Sperrlisten',
  'Create new' => 'Neu erstellen',
  'Update' => 'Aktualisieren',
  'Cannot open export temporary file!' => 'Die temporäre Exportdatei kann nicht geöffnet werden!',
  'Your file does not contain the header with the fields title!' => 'Ihre Datei enthält nicht die Kopfzeile mit den Feldtiteln!',
  'Your file has been successfuly imported, from {count} records, {total} were imported!' => 'Ihre Datei wurde erfolgreich importiert, von {count} Einträgen wurden {total} importiert!',
  'Unable to move the uploaded file!' => 'Die hochgeladene Datei kann nicht verschoben werden!',
  'Your file has been successfully queued for processing and you will be notified when processing is done!' => 'Ihre Datei wurde erfolgreich zur Verarbeitung eingereiht, und Sie werden benachrichtigt, wenn die Verarbeitung abgeschlossen ist!',
  'Import from CSV file' => 'Import aus CSV-Datei',
  'Please note, the csv file must contain a header with the email column.' => 'Bitte beachten Sie, dass die CSV-Datei eine Kopfzeile mit der E-Mail-Spalte enthalten muss.',
  'If unsure about how to format your file, do an export first and see how the file looks.' => 'Wenn Sie unsicher sind, wie Sie Ihre Datei formatieren sollen, führen Sie zuerst einen Export durch und sehen Sie sich die Datei an.',
);
