<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "survey_segments" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Segments' => 'Segments',
  'Segment' => 'Segment',
  'Survey' => 'Survey',
  'Name' => 'Name',
  'Operator match' => 'Operator match',
  'Responders count' => 'Responders count',
  'Condition' => 'Condition',
  'Operator' => 'Operator',
  'Field' => 'Field',
  'Value' => 'Value',
  'It will be transformed into an empty value' => 'It will be transformed into an empty value',
  'It will be transformed into the current date/time in the format of Y-m-d H:i:s (i.e: {datetime})' => 'It will be transformed into the current date/time in the format of Y-m-d H:i:s (i.e: {datetime})',
  'It will be transformed into the current date in the format of Y-m-d (i.e: {date})' => 'It will be transformed into the current date in the format of Y-m-d (i.e: {date})',
  'Your mail survey segments' => 'Your mail survey segments',
  'Survey segments' => 'Survey segments',
  ' Survey segments' => ' Survey segments',
  'You are only allowed to add {num} segment conditions.' => 'You are only allowed to add {num} segment conditions.',
  'Current segmentation is too deep and loads too slow, please revise your segment conditions!' => 'Current segmentation is too deep and loads too slow, please revise your segment conditions!',
  'Your survey segments' => 'Your survey segments',
  'Create a new survey segment' => 'Create a new survey segment',
  'Update survey segment' => 'Update survey segment',
  'Your survey segment was successfully copied!' => 'Your survey segment was successfully copied!',
  'This segment contains {count} responders' => 'This segment contains {count} responders',
  'Sorry, but there are no responders matching your segment.' => 'Sorry, but there are no responders matching your segment.',
  'Defined conditions:' => 'Defined conditions:',
  'Responders matching your segment:' => 'Responders matching your segment:',
  'Available value tags' => 'Available value tags',
  'Following tags can be used as dynamic values. They will be replaced as shown below.' => 'Following tags can be used as dynamic values. They will be replaced as shown below.',
  'Tag' => 'Tag',
  'Description' => 'Description',
);
