<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "survey_segments" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Segments' => 'Segmente',
    'Segment' => 'Segment',
    'Survey' => 'Umfrage',
    'Name' => 'Name',
    'Operator match' => 'Operator-Abgleich',
    'Responders count' => 'Anzahl der Teilnehmer',
    'Condition' => 'Bedingung',
    'Operator' => 'Operator',
    'Field' => 'Feld',
    'Value' => 'Wert',
    'It will be transformed into an empty value' => 'Es wird in einen leeren Wert umgewandelt',
    'It will be transformed into the current date/time in the format of Y-m-d H:i:s (i.e: {datetime})' => 'Es wird in das aktuelle Datum/Uhrzeit im Format Y-m-d H:i:s umgewandelt (z.B.: {datetime})',
    'It will be transformed into the current date in the format of Y-m-d (i.e: {date})' => 'Es wird in das aktuelle Datum im Format Y-m-d umgewandelt (z.B.: {date})',
    'Your mail survey segments' => 'Ihre E-Mail-Umfrage-Segmente',
    'Survey segments' => 'Umfrage-Segmente',
    ' Survey segments' => ' Umfrage-Segmente',
    'You are only allowed to add {num} segment conditions.' => 'Sie dürfen nur {num} Segmentbedingungen hinzufügen.',
    'Current segmentation is too deep and loads too slow, please revise your segment conditions!' => 'Die aktuelle Segmentierung ist zu tief und lädt zu langsam, bitte überarbeiten Sie Ihre Segmentbedingungen!',
    'Your survey segments' => 'Ihre Umfrage-Segmente',
    'Create a new survey segment' => 'Ein neues Umfrage-Segment erstellen',
    'Update survey segment' => 'Umfrage-Segment aktualisieren',
    'Your survey segment was successfully copied!' => 'Ihr Umfrage-Segment wurde erfolgreich kopiert!',
    'This segment contains {count} responders' => 'Dieses Segment enthält {count} Teilnehmer',
    'Sorry, but there are no responders matching your segment.' => 'Entschuldigung, aber es gibt keine Teilnehmer, die Ihrem Segment entsprechen.',
    'Defined conditions:' => 'Definierte Bedingungen:',
    'Responders matching your segment:' => 'Teilnehmer, die Ihrem Segment entsprechen:',
    'Available value tags' => 'Verfügbare Wert-Tags',
    'Following tags can be used as dynamic values. They will be replaced as shown below.' => 'Die folgenden Tags können als dynamische Werte verwendet werden. Sie werden wie unten gezeigt ersetzt.',
    'Tag' => 'Tag',
    'Description' => 'Beschreibung',
);
