<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "survey_export" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Export responders from your survey segment' => 'Exportieren Sie Teilnehmer aus Ihrem Umfrage-Segment',
  'Export responders' => 'Teilnehmer exportieren',
  'CSV Export' => 'CSV-Export',
  'Your survey has no responders to export!' => 'Ihre Umfrage hat keine Teilnehmer zum Exportieren!',
  'Cannot create the storage directory for your export!' => 'Das Speicherverzeichnis für Ihren Export kann nicht erstellt werden!',
  'Cannot open the storage file for your export!' => 'Die Speicherdatei für Ihren Export kann nicht geöffnet werden!',
  'Successfully added the IP "{ip}" to the export survey.' => 'Die IP "{ip}" wurde erfolgreich zur Export-Umfrage hinzugefügt.',
  'Exported {count} responders, from {start} to {end}.' => '{count} Teilnehmer exportiert, von {start} bis {end}.',
  'The export is now complete, starting the packing process...' => 'Der Export ist abgeschlossen, der Verpackungsprozess wird gestartet...',
  'Packing done, your file will be downloaded now, please wait...' => 'Verpackung abgeschlossen, Ihre Datei wird jetzt heruntergeladen, bitte warten...',
  'Please wait, starting another batch...' => 'Bitte warten, ein weiterer Durchlauf wird gestartet...',
  'The export file has been deleted.' => 'Die Exportdatei wurde gelöscht.',
  'Export segment' => 'Segment exportieren',
  'CSV' => 'CSV',
  'Click to export' => 'Zum Exportieren klicken',
  'CSV export progress' => 'CSV-Exportfortschritt',
  'Back to export options' => 'Zurück zu den Exportoptionen',
  'From a total of {total} responders, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.' => 'Von insgesamt {total} Teilnehmern wurden bisher {totalProcessed} verarbeitet, {successfullyProcessed} erfolgreich und {errorProcessing} mit Fehlern. {percentage} abgeschlossen.',
  'The export process is starting, please wait...' => 'Der Exportprozess wird gestartet, bitte warten...',
);
