<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "survey_responders" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Responders' => 'Teilnehmer',
    'Unique ID' => 'Eindeutige ID',
    'Your survey responders' => 'Ihre Umfrageteilnehmer',
    'Survey responders' => 'Umfrageteilnehmer',
    'Add a new responder to your survey.' => 'Fügen Sie Ihrer Umfrage einen neuen Teilnehmer hinzu.',
    'You are not allowed to edit responders at this time!' => 'Sie dürfen Teilnehmer derzeit nicht bearbeiten!',
    'Update existing survey responder.' => 'Vorhandenen Umfrageteilnehmer aktualisieren.',
    'Your survey responder was successfully deleted!' => 'Ihr Umfrageteilnehmer wurde erfolgreich gelöscht!',
    'Found {count} responders.' => '{count} Teilnehmer gefunden.',
    'Sorry, but there are no responders to show right now.' => 'Entschuldigung, es gibt derzeit keine Teilnehmer anzuzeigen.',
);
