<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "surveys" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Surveys' => 'Surveys',
  'Survey overview' => 'Survey overview',
  'Overview' => 'Overview',
  'Confirm survey removal' => 'Confirm survey removal',
  'Survey' => 'Survey',
  'View' => 'View',
  'This action will remove {responders} responders and {fields} custom fields.' => 'This action will remove {responders} responders and {fields} custom fields.',
  'Are you still sure you want to remove this survey? There is no coming back after you do it!' => 'Are you still sure you want to remove this survey? There is no coming back after you do it!',
  'Customer' => 'Customer',
  'Name' => 'Name',
  'Display name' => 'Display name',
  'Description' => 'Description',
  'Start at' => 'Start at',
  'End at' => 'End at',
  'Finish redirect' => 'Finish redirect',
  'Meta data' => 'Meta data',
  'Responders count' => 'Responders count',
  'The name of the survey' => 'The name of the survey',
  'The display name of the survey which will be shown to responders. If this is left blank, the name of the survey is shown instead' => 'The display name of the survey which will be shown to responders. If this is left blank, the name of the survey is shown instead',
  'The survey description shown to your responders' => 'The survey description shown to your responders',
  'The start date since this survey will be available' => 'The start date since this survey will be available',
  'The date when this survey will not be available anymore' => 'The date when this survey will not be available anymore',
  'Url where to redirect when the responder is reaching the survey end' => 'Url where to redirect when the responder is reaching the survey end',
  'Survey name, i.e: Customer satisfaction survey.' => 'Survey name, i.e: Customer satisfaction survey.',
  'Survey detailed description, something your responders will easily recognize.' => 'Survey detailed description, something your responders will easily recognize.',
  'i.e: https://www.google.com' => 'i.e: https://www.google.com',
  'Responder' => 'Responder',
  'Responder uid' => 'Responder uid',
  'Subscriber' => 'Subscriber',
  'Ip address' => 'Ip address',
  'Update' => 'Update',
  'Responders' => 'Responders',
  'Custom fields' => 'Custom fields',
  'Last 7 days responders activity' => 'Last 7 days responders activity',
  'Without response' => 'Without response',
  'With response' => 'With response',
  'Segments' => 'Segments',
  'Confirm survey segment removal' => 'Confirm survey segment removal',
  'Your surveys' => 'Your surveys',
  'You have reached the maximum number of allowed surveys.' => 'You have reached the maximum number of allowed surveys.',
  'Create new survey' => 'Create new survey',
  'Update survey' => 'Update survey',
  'Your survey was successfully copied!' => 'Your survey was successfully copied!',
  'The maximum number of allowed responders has been reached.' => 'The maximum number of allowed responders has been reached.',
  'The maximum number of allowed responders for this survey has been reached.' => 'The maximum number of allowed responders for this survey has been reached.',
  'Are you still sure you want to remove this survey segment? There is no coming back after you do it!' => 'Are you still sure you want to remove this survey segment? There is no coming back after you do it!',
  'Please use the date/time picker to set the value, do not enter it manually!' => 'Please use the date/time picker to set the value, do not enter it manually!',
  'This survey has no fields yet.' => 'This survey has no fields yet.',
  'This survey hasn\'t started yet!' => 'This survey hasn\'t started yet!',
  'This survey has ended!' => 'This survey has ended!',
  'We detected too many submissions from your IP address in a short period of time, please slow down!' => 'We detected too many submissions from your IP address in a short period of time, please slow down!',
  'Submit' => 'Submit',
  'Thank you!' => 'Thank you!',
  'draft' => 'draft',
  'active' => 'active',
  'inactive' => 'inactive',
  'The survey "{surveyName}" has been successfully created!' => 'The survey "{surveyName}" has been successfully created!',
  'The survey "{surveyName}" has been successfully updated!' => 'The survey "{surveyName}" has been successfully updated!',
  'The survey "{surveyName}" has been successfully deleted!' => 'The survey "{surveyName}" has been successfully deleted!',
  'Max responder allowed responses' => 'Max responder allowed responses',
  'How many responses a responder is allowed to have. Choose -1 for unlimited. We consider them unique based on their IPs or their subscriber_id' => 'How many responses a responder is allowed to have. Choose -1 for unlimited. We consider them unique based on their IPs or their subscriber_id',
);
