<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "survey_responders" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Responders' => 'Responders',
  'Unique ID' => 'Unique ID',
  'Your survey responders' => 'Your survey responders',
  'Survey responders' => 'Survey responders',
  'Add a new responder to your survey.' => 'Add a new responder to your survey.',
  'You are not allowed to edit responders at this time!' => 'You are not allowed to edit responders at this time!',
  'Update existing survey responder.' => 'Update existing survey responder.',
  'Your survey responder was successfully deleted!' => 'Your survey responder was successfully deleted!',
  'Found {count} responders.' => 'Found {count} responders.',
  'Sorry, but there are no responders to show right now.' => 'Sorry, but there are no responders to show right now.',
);
