<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "taxes" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View taxes' => 'View taxes',
  'Taxes' => 'Taxes',
  'Create new tax' => 'Create new tax',
  'Update tax' => 'Update tax',
  'Tax' => 'Tax',
  'Country' => 'Country',
  'Zone' => 'Zone',
  'Name' => 'Name',
  'Percent' => 'Percent',
  'Is global' => 'Is global',
  'The country for which this tax applies' => 'The country for which this tax applies',
  'The zone/state for which this tax applies' => 'The zone/state for which this tax applies',
  'The name of this tax' => 'The name of this tax',
  'How much from the total amount of the order this max means, use a number' => 'How much from the total amount of the order this max means, use a number',
  'Whether this tax is global, i.e: applies for customers that don\'t match other taxes' => 'Whether this tax is global, i.e: applies for customers that don\'t match other taxes',
);
