<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "taxes" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'View taxes' => 'Steuern anzeigen',
    'Taxes' => 'Steuern',
    'Create new tax' => 'Neue Steuer erstellen',
    'Update tax' => 'Steuer aktualisieren',
    'Tax' => 'Steuer',
    'Country' => 'Land',
    'Zone' => 'Zone',
    'Name' => 'Name',
    'Percent' => 'Prozent',
    'Is global' => 'Ist global',
    'The country for which this tax applies' => 'Das Land, für das diese Steuer gilt',
    'The zone/state for which this tax applies' => 'Die Zone/der Staat, für die/das diese Steuer gilt',
    'The name of this tax' => 'Der Name dieser Steuer',
    'How much from the total amount of the order this max means, use a number' => 'Wie viel vom Gesamtbetrag der Bestellung diese Steuer ausmacht, verwenden Sie eine Zahl',
    'Whether this tax is global, i.e: applies for customers that don\'t match other taxes' => 'Ob diese Steuer global ist, d.h. für Kunden gilt, die nicht zu anderen Steuern passen',
);
