<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "templates" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    '[TEST TEMPLATE] {name}' => '[TESTVORLAGE] {name}',
    'Subject' => 'Betreff',
    'Recipient(s)' => 'Empfänger',
    'i.e: a@domain.com, b@domain.com, c@domain.com' => 'z.B.: a@domain.com, b@domain.com, c@domain.com',
    'From email (optional)' => 'Von E-Mail (optional)',
    'i.e: me@domain.com' => 'z.B.: me@domain.com',
    '*** TEST TEMPLATE *** {name}' => '*** TESTVORLAGE *** {name}',
);
