<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "the_checker_co" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Add to queue for bulk check via TheChecker.co' => 'Zur Warteschlange für die Massenprüfung über TheChecker.co hinzufügen',
    'Remove from queue for bulk check via TheChecker.co' => 'Aus der Warteschlange für die Massenprüfung über TheChecker.co entfernen',
    'TheChecker.co' => 'TheChecker.co',
);
