<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "themes" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'View themes' => 'Themen anzeigen',
    'Themes' => 'Themen',
    'Theme settings' => 'Themen-Einstellungen',
    'Your theme has been successfully uploaded!' => 'Ihr Thema wurde erfolgreich hochgeladen!',
    'Please select a theme archive for upload!' => 'Bitte wählen Sie ein Themenarchiv zum Hochladen aus!',
    'The theme "{name}" has been successfully enabled!' => 'Das Thema "{name}" wurde erfolgreich aktiviert!',
    'The theme "{name}" has been successfully disabled!' => 'Das Thema "{name}" wurde erfolgreich deaktiviert!',
    'The theme "{name}" has been successfully deleted!' => 'Das Thema "{name}" wurde erfolgreich gelöscht!',
    'Available themes' => 'Verfügbare Themen',
    'Upload theme' => 'Thema hochladen',
    'Name' => 'Name',
    'Description' => 'Beschreibung',
    'Version' => 'Version',
    'Author' => 'Autor',
    'Website' => 'Webseite',
    'Theme detail page' => 'Themen-Detailseite',
    'Upload theme archive.' => 'Themenarchiv hochladen.',
    'Please note that only zip files are allowed for upload.' => 'Bitte beachten Sie, dass nur ZIP-Dateien hochgeladen werden dürfen.',
    'Visit website' => 'Webseite besuchen',
    'The theme does not exists.' => 'Das Thema existiert nicht.',
    'The theme is already enabled.' => 'Das Thema ist bereits aktiviert.',
    'Enabling the theme {theme} has failed.' => 'Das Aktivieren des Themas {theme} ist fehlgeschlagen.',
    'The theme could not be disabled.' => 'Das Thema konnte nicht deaktiviert werden.',
    'The theme cannot be deleted.' => 'Das Thema kann nicht gelöscht werden.',
);
