<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "tools" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Back to tools' => 'Zurück zu den Tools',
    'Sync' => 'Synchronisieren',
    'Subscribers' => 'Abonnenten',
    'Split' => 'Teilen',
    'List' => 'Liste',
    'Sync lists' => 'Listen synchronisieren',
    'Split list' => 'Liste teilen',
    'Please wait while splitting the {list} list into {num} sublists. This might take a while depending on your list size.' => 'Bitte warten Sie, während die Liste {list} in {num} Unterlisten aufgeteilt wird. Dies kann je nach Größe der Liste eine Weile dauern.',
);
