<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "tour" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Are you sure? The tour contains valuable information to help you get started. You will not see the tour again if you end it!' => 'Sind Sie sicher? Die Tour enthält wertvolle Informationen, die Ihnen den Einstieg erleichtern. Sie werden die Tour nicht erneut sehen, wenn Sie sie beenden!',
    'End the tour' => 'Tour beenden',
    'Close for now' => 'Für jetzt schließen',
    'Tour' => 'Tour',
    'Common' => 'Allgemein',
    'Slideshows' => 'Diashows',
    'Backend' => 'Backend',
    'Customer' => 'Kunde',
    'View slideshows' => 'Diashows anzeigen',
    'View slides' => 'Folien anzeigen',
    'Slideshow' => 'Diashow',
    'Name' => 'Name',
    'Application' => 'Anwendung',
    'Slides count' => 'Anzahl der Folien',
    'customer' => 'kunde',
    'backend' => 'backend',
);
