<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "tour" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Are you sure? The tour contains valuable information to help you get started. You will not see the tour again if you end it!' => 'Are you sure? The tour contains valuable information to help you get started. You will not see the tour again if you end it!',
  'End the tour' => 'End the tour',
  'Close for now' => 'Close for now',
  'Tour' => 'Tour',
  'Common' => 'Common',
  'Slideshows' => 'Slideshows',
  'Backend' => 'Backend',
  'Customer' => 'Customer',
  'View slideshows' => 'View slideshows',
  'View slides' => 'View slides',
  'Slideshow' => 'Slideshow',
  'Name' => 'Name',
  'Application' => 'Application',
  'Slides count' => 'Slides count',
  'customer' => 'customer',
  'backend' => 'backend',
);
