<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "tracking_domains" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View tracking domains' => 'View tracking domains',
  'Tracking domains' => 'Tracking domains',
  'Create new tracking domain' => 'Create new tracking domain',
  'Update tracking domain' => 'Update tracking domain',
  'Please note, in order for this feature to work this (sub)domain needs a dedicated IP address, otherwise all defined CNAMES for it will point to the default domain on this server.' => 'Please note, in order for this feature to work this (sub)domain needs a dedicated IP address, otherwise all defined CNAMES for it will point to the default domain on this server.',
  'If you do not use a dedicated IP address for this domain only or you are not sure you do so, do not use this feature!' => 'If you do not use a dedicated IP address for this domain only or you are not sure you do so, do not use this feature!',
  'Please note that because of the way DNS servers work, you need to add a subdomain like tracking.your-domain.com as a DNS CNAME record and point it to {currentDomain}!' => 'Please note that because of the way DNS servers work, you need to add a subdomain like tracking.your-domain.com as a DNS CNAME record and point it to {currentDomain}!',
  'Domain' => 'Domain',
  'Customer' => 'Customer',
  'Name' => 'Name',
  'Scheme' => 'Scheme',
  'Skip validation' => 'Skip validation',
  'tracking.your-domain.com' => 'tracking.your-domain.com',
  'Please DO NOT SKIP validation unless you are 100% sure you know what you are doing.' => 'Please DO NOT SKIP validation unless you are 100% sure you know what you are doing.',
  'Choose HTTPS only if your tracking domain can also provide a valid SSL certificate, otherwise stick to regular HTTP.' => 'Choose HTTPS only if your tracking domain can also provide a valid SSL certificate, otherwise stick to regular HTTP.',
  'Unable to get the current domain name!' => 'Unable to get the current domain name!',
  'Your specified domain name does not seem to be valid!' => 'Your specified domain name does not seem to be valid!',
  'Your PHP install does not contain the {function} function needed to query the DNS records!' => 'Your PHP install does not contain the {function} function needed to query the DNS records!',
  'Cannot find a valid CNAME record for {domainName}! Remember, the CNAME of {domainName} must point to {currentDomain}!' => 'Cannot find a valid CNAME record for {domainName}! Remember, the CNAME of {domainName} must point to {currentDomain}!',
  'Verified' => 'Verified',
  'Skip verification' => 'Skip verification',
  'Please DO NOT SKIP verification unless you are 100% sure you know what you are doing.' => 'Please DO NOT SKIP verification unless you are 100% sure you know what you are doing.',
  'Domain ID' => 'Domain ID',
);
