<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "tracking_domains" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'View tracking domains' => 'Tracking-Domains anzeigen',
    'Tracking domains' => 'Tracking-Domains',
    'Create new tracking domain' => 'Neue Tracking-Domain erstellen',
    'Update tracking domain' => 'Tracking-Domain aktualisieren',
    'Please note, in order for this feature to work this (sub)domain needs a dedicated IP address, otherwise all defined CNAMES for it will point to the default domain on this server.' => 'Bitte beachten Sie, dass für diese Funktion diese (Sub-)Domain eine dedizierte IP-Adresse benötigt, da andernfalls alle definierten CNAMES darauf auf die Standarddomain auf diesem Server verweisen.',
    'If you do not use a dedicated IP address for this domain only or you are not sure you do so, do not use this feature!' => 'Wenn Sie keine dedizierte IP-Adresse ausschließlich für diese Domain verwenden oder sich nicht sicher sind, tun Sie dies nicht, verwenden Sie diese Funktion nicht!',
    'Please note that because of the way DNS servers work, you need to add a subdomain like tracking.your-domain.com as a DNS CNAME record and point it to {currentDomain}!' => 'Bitte beachten Sie, dass Sie aufgrund der Funktionsweise von DNS-Servern eine Subdomain wie tracking.ihre-domain.com als DNS-CNAME-Eintrag hinzufügen und auf {currentDomain} verweisen müssen!',
    'Domain' => 'Domain',
    'Customer' => 'Kunde',
    'Name' => 'Name',
    'Scheme' => 'Schema',
    'Skip validation' => 'Validierung überspringen',
    'tracking.your-domain.com' => 'tracking.ihre-domain.com',
    'Please DO NOT SKIP validation unless you are 100% sure you know what you are doing.' => 'Bitte überspringen Sie die Validierung NICHT, es sei denn, Sie sind sich zu 100 % sicher, was Sie tun.',
    'Choose HTTPS only if your tracking domain can also provide a valid SSL certificate, otherwise stick to regular HTTP.' => 'Wählen Sie HTTPS nur, wenn Ihre Tracking-Domain auch ein gültiges SSL-Zertifikat bereitstellen kann, andernfalls bleiben Sie bei regulärem HTTP.',
    'Unable to get the current domain name!' => 'Der aktuelle Domainname kann nicht abgerufen werden!',
    'Your specified domain name does not seem to be valid!' => 'Der angegebene Domainname scheint ungültig zu sein!',
    'Your PHP install does not contain the {function} function needed to query the DNS records!' => 'Ihre PHP-Installation enthält nicht die {function}-Funktion, die zum Abfragen der DNS-Einträge erforderlich ist!',
    'Cannot find a valid CNAME record for {domainName}! Remember, the CNAME of {domainName} must point to {currentDomain}!' => 'Es konnte kein gültiger CNAME-Eintrag für {domainName} gefunden werden! Denken Sie daran, dass der CNAME von {domainName} auf {currentDomain} verweisen muss!',
    'Verified' => 'Verifiziert',
    'Skip verification' => 'Verifizierung überspringen',
    'Please DO NOT SKIP verification unless you are 100% sure you know what you are doing.' => 'Bitte überspringen Sie die Verifizierung NICHT, es sei denn, Sie sind sich zu 100 % sicher, was Sie tun.',
    'Domain ID' => 'Domain-ID',
);
