<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "transactional_emails" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'View transactional emails' => 'Transaktions-E-Mails anzeigen',
    'Transactional emails' => 'Transaktions-E-Mails',
    'Log' => 'Protokoll',
    'Email' => 'E-Mail',
    'Message' => 'Nachricht',
    'Customer' => 'Kunde',
    'To email' => 'An E-Mail',
    'To name' => 'An Name',
    'From email' => 'Von E-Mail',
    'From name' => 'Von Name',
    'Reply to email' => 'Antwort an E-Mail',
    'Reply to name' => 'Antwort an Name',
    'Subject' => 'Betreff',
    'Body' => 'Inhalt',
    'Plain text' => 'Nur-Text',
    'Priority' => 'Priorität',
    'Retries' => 'Wiederholungen',
    'Max retries' => 'Maximale Wiederholungen',
    'Send at' => 'Senden um',
    'This email address is blacklisted!' => 'Diese E-Mail-Adresse ist auf der Sperrliste!',
    'Sent' => 'Gesendet',
    'Unsent' => 'Nicht gesendet',
    'Failed' => 'Fehlgeschlagen',
    'Transactional emails dashboard' => 'Transaktions-E-Mails-Dashboard',
    'Total' => 'Gesamt',
    'View unsent transactional emails' => 'Nicht gesendete Transaktions-E-Mails anzeigen',
    'View sent transactional emails' => 'Gesendete Transaktions-E-Mails anzeigen',
    'View transactional emails cron jobs history' => 'Cron-Job-Historie der Transaktions-E-Mails anzeigen',
);
