<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "translate" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Enable automatic translation' => 'Enable automatic translation',
  'Enable extensions translation' => 'Enable extensions translation',
  'Enable writing the missing translations in file.' => 'Enable writing the missing translations in file.',
  'Whether to translate extensions too.' => 'Whether to translate extensions too.',
  'Translate extension' => 'Translate extension',
  'The directory {dirName} must exist and be writable by the web server in order to write the translation files.' => 'The directory {dirName} must exist and be writable by the web server in order to write the translation files.',
  'Translation extension' => 'Translation extension',
  'Once enabled, the translate extension will start collecting messages from the application and write them in files if the message is missing from file and the application language is other than english.' => 'Once enabled, the translate extension will start collecting messages from the application and write them in files if the message is missing from file and the application language is other than english.',
);
