<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "translate" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Enable automatic translation' => 'Automatische Übersetzung aktivieren',
    'Enable extensions translation' => 'Übersetzung von Erweiterungen aktivieren',
    'Enable writing the missing translations in file.' => 'Fehlende Übersetzungen in Datei schreiben aktivieren.',
    'Whether to translate extensions too.' => 'Ob auch Erweiterungen übersetzt werden sollen.',
    'Translate extension' => 'Erweiterung übersetzen',
    'The directory {dirName} must exist and be writable by the web server in order to write the translation files.' => 'Das Verzeichnis {dirName} muss existieren und vom Webserver beschreibbar sein, um die Übersetzungsdateien zu schreiben.',
    'Translation extension' => 'Übersetzungserweiterung',
    'Once enabled, the translate extension will start collecting messages from the application and write them in files if the message is missing from file and the application language is other than english.' => 'Sobald aktiviert, beginnt die Übersetzungserweiterung, Nachrichten aus der Anwendung zu sammeln und in Dateien zu schreiben, wenn die Nachricht in der Datei fehlt und die Anwendungssprache nicht Englisch ist.',
);
