<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "translations" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Category' => 'Kategorie',
    'Message' => 'Nachricht',
    'Translation' => 'Übersetzung',
    'Please make sure you save your changes before navigating away to a different page.' => 'Bitte stellen Sie sicher, dass Sie Ihre Änderungen speichern, bevor Sie zu einer anderen Seite navigieren.',
    '{name} translations' => '{name} Übersetzungen',
    'Translations' => 'Übersetzungen',
    'Language' => 'Sprache',
);
