<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "update" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Please note that starting with this version update, we deprecated the redis queue feature!' => 'Bitte beachten Sie, dass mit diesem Versionsupdate die Redis-Queue-Funktion eingestellt wurde!',
    'Version {version} brings a new cron job that you have to add to run once at 20 minutes. After addition, it must look like: {cron}' => 'Version {version} bringt einen neuen Cron-Job, den Sie hinzufügen müssen, um einmal alle 20 Minuten ausgeführt zu werden. Nach der Hinzufügung sollte er wie folgt aussehen: {cron}',
    'Version {version} brings a new cron job that you have to add to run once a day. After addition, it must look like: {cron}' => 'Version {version} bringt einen neuen Cron-Job, den Sie hinzufügen müssen, um einmal täglich ausgeführt zu werden. Nach der Hinzufügung sollte er wie folgt aussehen: {cron}',
    'Starting with version {version}, the "process-subscribers" command is no longer needed, please disable it from your crons!' => 'Ab Version {version} wird der Befehl "process-subscribers" nicht mehr benötigt. Bitte deaktivieren Sie ihn in Ihren Crons!',
    'Version {version} brings a new cron job that you have to add to run each hour. After addition, it must look like: {cron}' => 'Version {version} bringt einen neuen Cron-Job, den Sie hinzufügen müssen, um stündlich ausgeführt zu werden. Nach der Hinzufügung sollte er wie folgt aussehen: {cron}',
    'Version {version} brings a new cron job that you have to add to run once at 2 minutes. After addition, it must look like: {cron}' => 'Version {version} bringt einen neuen Cron-Job, den Sie hinzufügen müssen, um einmal alle 2 Minuten ausgeführt zu werden. Nach der Hinzufügung sollte er wie folgt aussehen: {cron}',
    'This version adds new fields for delivery servers and some of them are required. Because of this, all delivery servers have been marked as inactive. Please review the settings and validate the servers once again.' => 'Diese Version fügt neue Felder für Zustellserver hinzu, von denen einige erforderlich sind. Aus diesem Grund wurden alle Zustellserver als inaktiv markiert. Bitte überprüfen Sie die Einstellungen und validieren Sie die Server erneut.',
    'Updating to version {version}.' => 'Aktualisierung auf Version {version}.',
    'Updated to version {version} successfully.' => 'Erfolgreich auf Version {version} aktualisiert.',
    'Updating to version {version} failed with: {message}' => 'Aktualisierung auf Version {version} fehlgeschlagen mit: {message}',
    'Congratulations, your application has been successfully updated to version {version}' => 'Herzlichen Glückwunsch, Ihre Anwendung wurde erfolgreich auf Version {version} aktualisiert',
    'Please note, depending on your database size it is better to run the command line update tool instead.' => 'Bitte beachten Sie, dass es je nach Größe Ihrer Datenbank besser ist, das Befehlszeilen-Update-Tool zu verwenden.',
    'In order to run the command line update tool, you must run the following command from a ssh shell:' => 'Um das Befehlszeilen-Update-Tool auszuführen, müssen Sie den folgenden Befehl in einer SSH-Shell ausführen:',
    'Update' => 'Aktualisieren',
    'Application update' => 'Anwendungsaktualisierung',
    'Update application' => 'Anwendung aktualisieren',
    'Your current application version is {version}' => 'Ihre aktuelle Anwendungsversion ist {version}',
    'The update process will try to update it to version {version}' => 'Der Aktualisierungsprozess versucht, sie auf Version {version} zu aktualisieren',
    'Please backup all your data before proceeding and note that the update process might take a while depending on your database size, just wait for it to finish.' => 'Bitte sichern Sie alle Ihre Daten, bevor Sie fortfahren, und beachten Sie, dass der Aktualisierungsprozess je nach Größe Ihrer Datenbank einige Zeit in Anspruch nehmen kann. Warten Sie einfach, bis er abgeschlossen ist.',
    'Your application has been moved offline until the update process is done.' => 'Ihre Anwendung wurde offline geschaltet, bis der Aktualisierungsprozess abgeschlossen ist.',
    'Start update process' => 'Aktualisierungsprozess starten',
);
