<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "users" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Remember me' => 'Remember me',
  '2FA code' => '2FA code',
  'Invalid login credentials.' => 'Invalid login credentials.',
  'Unable to login with the given identity!' => 'Unable to login with the given identity!',
  'View users' => 'View users',
  'Users' => 'Users',
  'Create new user' => 'Create new user',
  'You are not allowed to update the master administrator!' => 'You are not allowed to update the master administrator!',
  'Update user' => 'Update user',
  'Update account' => 'Update account',
  'User info successfully updated!' => 'User info successfully updated!',
  '2FA' => '2FA',
  'Please login' => 'Please login',
  'Retrieve a new password for your account.' => 'Retrieve a new password for your account.',
  'Update user group' => 'Update user group',
  'Use any authenticator app such as Google Authenticator to scan the QR code below.' => 'Use any authenticator app such as Google Authenticator to scan the QR code below.',
  'You will then use the authenticator app to generate the code to login in the app.' => 'You will then use the authenticator app to generate the code to login in the app.',
  'Sign in to start your session' => 'Sign in to start your session',
  'Forgot password?' => 'Forgot password?',
  'Go to login' => 'Go to login',
  'Enter the code generated by the authenticator app' => 'Enter the code generated by the authenticator app',
  'Update your account data.' => 'Update your account data.',
  'User' => 'User',
  'Language' => 'Language',
  'Group' => 'Group',
  'First name' => 'First name',
  'Last name' => 'Last name',
  'Email' => 'Email',
  'Password' => 'Password',
  'Timezone' => 'Timezone',
  'Avatar' => 'Avatar',
  'New avatar' => 'New avatar',
  'Removable' => 'Removable',
  'Confirm email' => 'Confirm email',
  'Confirm password' => 'Confirm password',
  '2FA enabled' => '2FA enabled',
  'Please make sure you scan the QR code in your authenticator application before enabling this feature, otherwise you will be locked out from your account' => 'Please make sure you scan the QR code in your authenticator application before enabling this feature, otherwise you will be locked out from your account',
  'The avatars storage directory({path}) does not exists and cannot be created!' => 'The avatars storage directory({path}) does not exists and cannot be created!',
  'Cannot move the avatar into the correct storage folder!' => 'Cannot move the avatar into the correct storage folder!',
  'Request' => 'Request',
  'Reset key' => 'Reset key',
  'Ip address' => 'Ip address',
  'Token' => 'Token',
  'You are impersonating the customer {customerName}.' => 'You are impersonating the customer {customerName}.',
  'Please click {linkBack} to logout in order to finish impersonating.' => 'Please click {linkBack} to logout in order to finish impersonating.',
);
