<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "users" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'Remember me' => 'Angemeldet bleiben',
    '2FA code' => '2FA-Code',
    'Invalid login credentials.' => 'Ungültige Anmeldedaten.',
    'Unable to login with the given identity!' => 'Anmeldung mit der angegebenen Identität nicht möglich!',
    'View users' => 'Benutzer anzeigen',
    'Users' => 'Benutzer',
    'Create new user' => 'Neuen Benutzer erstellen',
    'You are not allowed to update the master administrator!' => 'Sie dürfen den Hauptadministrator nicht aktualisieren!',
    'Update user' => 'Benutzer aktualisieren',
    'Update account' => 'Konto aktualisieren',
    'User info successfully updated!' => 'Benutzerdaten erfolgreich aktualisiert!',
    '2FA' => '2FA',
    'Please login' => 'Bitte anmelden',
    'Retrieve a new password for your account.' => 'Ein neues Passwort für Ihr Konto anfordern.',
    'Update user group' => 'Benutzergruppe aktualisieren',
    'Use any authenticator app such as Google Authenticator to scan the QR code below.' => 'Verwenden Sie eine Authentifizierungs-App wie Google Authenticator, um den untenstehenden QR-Code zu scannen.',
    'You will then use the authenticator app to generate the code to login in the app.' => 'Sie verwenden dann die Authentifizierungs-App, um den Code für die Anmeldung in der App zu generieren.',
    'Sign in to start your session' => 'Melden Sie sich an, um Ihre Sitzung zu starten',
    'Forgot password?' => 'Passwort vergessen?',
    'Go to login' => 'Zur Anmeldung gehen',
    'Enter the code generated by the authenticator app' => 'Geben Sie den von der Authentifizierungs-App generierten Code ein',
    'Update your account data.' => 'Aktualisieren Sie Ihre Kontodaten.',
    'User' => 'Benutzer',
    'Language' => 'Sprache',
    'Group' => 'Gruppe',
    'First name' => 'Vorname',
    'Last name' => 'Nachname',
    'Email' => 'E-Mail',
    'Password' => 'Passwort',
    'Timezone' => 'Zeitzone',
    'Avatar' => 'Avatar',
    'New avatar' => 'Neuer Avatar',
    'Removable' => 'Entfernbar',
    'Confirm email' => 'E-Mail bestätigen',
    'Confirm password' => 'Passwort bestätigen',
    '2FA enabled' => '2FA aktiviert',
    'Please make sure you scan the QR code in your authenticator application before enabling this feature, otherwise you will be locked out from your account' => 'Bitte stellen Sie sicher, dass Sie den QR-Code in Ihrer Authentifizierungs-App scannen, bevor Sie diese Funktion aktivieren, da Sie sonst von Ihrem Konto ausgeschlossen werden.',
    'The avatars storage directory({path}) does not exists and cannot be created!' => 'Das Speicherverzeichnis für Avatare ({path}) existiert nicht und kann nicht erstellt werden!',
    'Cannot move the avatar into the correct storage folder!' => 'Der Avatar kann nicht in den richtigen Speicherordner verschoben werden!',
    'Request' => 'Anfrage',
    'Reset key' => 'Schlüssel zurücksetzen',
    'Ip address' => 'IP-Adresse',
    'Token' => 'Token',
    'You are impersonating the customer {customerName}.' => 'Sie geben sich als Kunde {customerName} aus.',
    'Please click {linkBack} to logout in order to finish impersonating.' => 'Bitte klicken Sie auf {linkBack}, um sich abzumelden und die Nachahmung zu beenden.',
);
