<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "warmup_plans" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'hourly' => 'hourly',
  'daily' => 'daily',
  'monthly' => 'monthly',
  'linear' => 'linear',
  'exponential' => 'exponential',
  'total' => 'total',
  'targeted' => 'targeted',
  'View plans' => 'View plans',
  'Warmup plans' => 'Warmup plans',
  'Delivery server warmup plan' => 'Delivery server warmup plan',
  'Customer' => 'Customer',
  'Name' => 'Name',
  'Description' => 'Description',
  'Sending limit' => 'Sending limit',
  'Sendings count' => 'Sendings count',
  'Sending quota type' => 'Sending quota type',
  'Sending increment percentage' => 'Sending increment percentage',
  'Sending strategy' => 'Sending strategy',
  'Sending limit type' => 'Sending limit type',
  'Are you sure you want to run this action? After you activate the plan, you will be able to edit only its name and description' => 'Are you sure you want to run this action? After you activate the plan, you will be able to edit only its name and description',
  'Update plan' => 'Update plan',
  'Active' => 'Active',
  'The warmup plan name' => 'The warmup plan name',
  'The warmup plan description' => 'The warmup plan description',
  'The warmup plan sending limit, meaning the number of emails to be sent. Based on the limit type chosen this number can be the total number of emails sent throughout all the sendings, or the last sending will have that exact number' => 'The warmup plan sending limit, meaning the number of emails to be sent. Based on the limit type chosen this number can be the total number of emails sent throughout all the sendings, or the last sending will have that exact number',
  'The warmup plan sendings count. This is the number of generated schedules, based on which the delivery server quota will apply.' => 'The warmup plan sendings count. This is the number of generated schedules, based on which the delivery server quota will apply.',
  'The warmup plan sending quota type. The kind of quota against which the generated schedule quota value will be applied. If hourly, we will take into consideration applying the delivery server hourly quota' => 'The warmup plan sending quota type. The kind of quota against which the generated schedule quota value will be applied. If hourly, we will take into consideration applying the delivery server hourly quota',
  'The warmup plan sending increment ratio. If the sending strategy is exponential, this values represents the increment percentage from a schedule to another.' => 'The warmup plan sending increment ratio. If the sending strategy is exponential, this values represents the increment percentage from a schedule to another.',
  'The warmup plan sending strategy. Can be exponential or incremental. For incremental we will use the ratio between sending_limit and sendings_count to calculate the growth factor. Depending on the sending limit type chosen we can send maximum the value of the growth factor per sending (for total) or the growth factor added to the previous sending value per sending (for targeted).' => 'The warmup plan sending strategy. Can be exponential or incremental. For incremental we will use the ratio between sending_limit and sendings_count to calculate the growth factor. Depending on the sending limit type chosen we can send maximum the value of the growth factor per sending (for total) or the growth factor added to the previous sending value per sending (for targeted).',
  'The warmup plan sending limit type. Based on this selection, we will send either a number of emails calculated throughout all the schedules (total) equal with the sending limit, or the last of the sendings will reach the sending limit value.' => 'The warmup plan sending limit type. Based on this selection, we will send either a number of emails calculated throughout all the schedules (total) equal with the sending limit, or the last of the sendings will reach the sending limit value.',
  'Generated warmup plan' => 'Generated warmup plan',
  'Schedule' => 'Schedule',
  'Increment' => 'Increment',
  'Quota' => 'Quota',
  'Warmup plan' => 'Warmup plan',
  'Please note that the last schedule from the series might be the subject to roundings.' => 'Please note that the last schedule from the series might be the subject to roundings.',
);
