<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "warmup_plans" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'hourly' => 'stündlich',
    'daily' => 'täglich',
    'monthly' => 'monatlich',
    'linear' => 'linear',
    'exponential' => 'exponentiell',
    'total' => 'gesamt',
    'targeted' => 'gezielt',
    'View plans' => 'Pläne anzeigen',
    'Warmup plans' => 'Aufwärmpläne',
    'Delivery server warmup plan' => 'Aufwärmplan für Zustellserver',
    'Customer' => 'Kunde',
    'Name' => 'Name',
    'Description' => 'Beschreibung',
    'Sending limit' => 'Sendelimit',
    'Sendings count' => 'Anzahl der Sendungen',
    'Sending quota type' => 'Art des Sendekontingents',
    'Sending increment percentage' => 'Prozentsatz der Sendeerhöhung',
    'Sending strategy' => 'Sendestrategie',
    'Sending limit type' => 'Art des Sendelimits',
    'Are you sure you want to run this action? After you activate the plan, you will be able to edit only its name and description' => 'Sind Sie sicher, dass Sie diese Aktion ausführen möchten? Nach der Aktivierung des Plans können Sie nur noch den Namen und die Beschreibung bearbeiten',
    'Update plan' => 'Plan aktualisieren',
    'Active' => 'Aktiv',
    'The warmup plan name' => 'Der Name des Aufwärmplans',
    'The warmup plan description' => 'Die Beschreibung des Aufwärmplans',
    'The warmup plan sending limit, meaning the number of emails to be sent. Based on the limit type chosen this number can be the total number of emails sent throughout all the sendings, or the last sending will have that exact number' => 'Das Sendelimit des Aufwärmplans, also die Anzahl der zu sendenden E-Mails. Basierend auf der gewählten Limitart kann diese Zahl die Gesamtanzahl der E-Mails sein, die über alle Sendungen hinweg gesendet werden, oder die letzte Sendung hat genau diese Zahl',
    'The warmup plan sendings count. This is the number of generated schedules, based on which the delivery server quota will apply.' => 'Die Anzahl der Sendungen des Aufwärmplans. Dies ist die Anzahl der generierten Zeitpläne, auf deren Grundlage das Zustellserver-Kontingent angewendet wird.',
    'The warmup plan sending quota type. The kind of quota against which the generated schedule quota value will be applied. If hourly, we will take into consideration applying the delivery server hourly quota' => 'Die Art des Sendekontingents des Aufwärmplans. Die Art des Kontingents, gegen das der generierte Zeitplanwert angewendet wird. Wenn stündlich, berücksichtigen wir die Anwendung des stündlichen Kontingents des Zustellservers',
    'The warmup plan sending increment ratio. If the sending strategy is exponential, this values represents the increment percentage from a schedule to another.' => 'Das Erhöhungsverhältnis des Aufwärmplans. Wenn die Sendestrategie exponentiell ist, stellt dieser Wert den Erhöhungsprozentsatz von einem Zeitplan zum anderen dar.',
    'The warmup plan sending strategy. Can be exponential or incremental. For incremental we will use the ratio between sending_limit and sendings_count to calculate the growth factor. Depending on the sending limit type chosen we can send maximum the value of the growth factor per sending (for total) or the growth factor added to the previous sending value per sending (for targeted).' => 'Die Sendestrategie des Aufwärmplans. Kann exponentiell oder inkrementell sein. Für inkrementell verwenden wir das Verhältnis zwischen Sendelimit und Anzahl der Sendungen, um den Wachstumsfaktor zu berechnen. Abhängig von der gewählten Art des Sendelimits können wir maximal den Wert des Wachstumsfaktors pro Sendung (für gesamt) oder den Wachstumsfaktor, der zum vorherigen Sendewert pro Sendung hinzugefügt wird (für gezielt), senden.',
    'The warmup plan sending limit type. Based on this selection, we will send either a number of emails calculated throughout all the schedules (total) equal with the sending limit, or the last of the sendings will reach the sending limit value.' => 'Die Art des Sendelimits des Aufwärmplans. Basierend auf dieser Auswahl senden wir entweder eine Anzahl von E-Mails, die über alle Zeitpläne hinweg berechnet wird (gesamt), gleich dem Sendelimit, oder die letzte der Sendungen erreicht den Wert des Sendelimits.',
    'Generated warmup plan' => 'Generierter Aufwärmplan',
    'Schedule' => 'Zeitplan',
    'Increment' => 'Erhöhung',
    'Quota' => 'Kontingent',
    'Warmup plan' => 'Aufwärmplan',
    'Please note that the last schedule from the series might be the subject to roundings.' => 'Bitte beachten Sie, dass der letzte Zeitplan der Serie Rundungen unterliegen kann.',
);
