<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "zii" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'The "dataProvider" property cannot be empty.' => 'Die Eigenschaft "dataProvider" darf nicht leer sein.',
    'No results found.' => 'Keine Ergebnisse gefunden.',
    'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Zeige {start}-{end} von 1 Ergebnis an.|Zeige {start}-{end} von {count} Ergebnissen an.',
    'Total 1 result.|Total {count} results.' => 'Insgesamt 1 Ergebnis.|Insgesamt {count} Ergebnisse.',
    'Home' => 'Startseite',
    'The property "itemView" cannot be empty.' => 'Die Eigenschaft "itemView" darf nicht leer sein.',
    'Sort by: ' => 'Sortieren nach: ',
    'Please specify the "data" property.' => 'Bitte geben Sie die Eigenschaft "data" an.',
    'Please specify the "attributes" property.' => 'Bitte geben Sie die Eigenschaft "attributes" an.',
    'Not set' => 'Nicht festgelegt',
    'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Das Attribut muss im Format "Name:Type:Label" angegeben werden, wobei "Type" und "Label" optional sind.',
    '{class} must specify "model" and "{attribute}" or "{name}" property values.' => '{class} muss die Eigenschaften "model" und "{attribute}" oder "{name}" angeben.',
    'The button type "{type}" is not supported.' => 'Der Button-Typ "{type}" wird nicht unterstützt.',
    'Either "name" or "value" must be specified for CDataColumn.' => 'Entweder "name" oder "value" muss für CDataColumn angegeben werden.',
    'The property updateSelector should be defined.' => 'Die Eigenschaft updateSelector sollte definiert sein.',
    'The property filterSelector should be defined.' => 'Die Eigenschaft filterSelector sollte definiert sein.',
    'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Die Spalte muss im Format "Name:Type:Label" angegeben werden, wobei "Type" und "Label" optional sind.',
    'View' => 'Anzeigen',
    'Update' => 'Aktualisieren',
    'Delete' => 'Löschen',
    'Are you sure you want to delete this item?' => 'Sind Sie sicher, dass Sie dieses Element löschen möchten?',
);
