<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "zii" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'The "dataProvider" property cannot be empty.' => 'The "dataProvider" property cannot be empty.',
  'No results found.' => 'No results found.',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.',
  'Total 1 result.|Total {count} results.' => 'Total 1 result.|Total {count} results.',
  'Home' => 'Home',
  'The property "itemView" cannot be empty.' => 'The property "itemView" cannot be empty.',
  'Sort by: ' => 'Sort by: ',
  'Please specify the "data" property.' => 'Please specify the "data" property.',
  'Please specify the "attributes" property.' => 'Please specify the "attributes" property.',
  'Not set' => 'Not set',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.',
  '{class} must specify "model" and "{attribute}" or "{name}" property values.' => '{class} must specify "model" and "{attribute}" or "{name}" property values.',
  'The button type "{type}" is not supported.' => 'The button type "{type}" is not supported.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Either "name" or "value" must be specified for CDataColumn.',
  'The property updateSelector should be defined.' => 'The property updateSelector should be defined.',
  'The property filterSelector should be defined.' => 'The property filterSelector should be defined.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.',
  'View' => 'View',
  'Update' => 'Update',
  'Delete' => 'Delete',
  'Are you sure you want to delete this item?' => 'Are you sure you want to delete this item?',
);
