<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "zones" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
    'View zones' => 'Zonen anzeigen',
    'Zones' => 'Zonen',
    'Create new zone' => 'Neue Zone erstellen',
    'Update zone' => 'Zone aktualisieren',
    'Confirm zone removal' => 'Entfernen der Zone bestätigen',
    'Please note that removing this zone will also remove every record that depends on it, such as taxes, customer companies, etc!' => 'Bitte beachten Sie, dass das Entfernen dieser Zone auch alle Datensätze entfernt, die davon abhängen, wie Steuern, Kundenunternehmen usw.!',
    'Are you still sure you want to remove this zone? There is no coming back after you do it!' => 'Sind Sie sicher, dass Sie diese Zone entfernen möchten? Dies kann nicht rückgängig gemacht werden!',
    'Zone' => 'Zone',
    'Country' => 'Land',
    'Name' => 'Name',
    'Code' => 'Code',
);
