<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "zones" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View zones' => 'View zones',
  'Zones' => 'Zones',
  'Create new zone' => 'Create new zone',
  'Update zone' => 'Update zone',
  'Confirm zone removal' => 'Confirm zone removal',
  'Please note that removing this zone will also remove every record that depends on it, such as taxes, customer companies, etc!' => 'Please note that removing this zone will also remove every record that depends on it, such as taxes, customer companies, etc!',
  'Are you still sure you want to remove this zone? There is no coming back after you do it!' => 'Are you still sure you want to remove this zone? There is no coming back after you do it!',
  'Zone' => 'Zone',
  'Country' => 'Country',
  'Name' => 'Name',
  'Code' => 'Code',
);
